Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2018-08, with the labels that each got.

#1285 Dev to alpha
  cluster/manifests/prometheus-node-exporter/daemonset.yaml
  cluster/manifests/prometheus/configmap.yaml
  cluster/manifests/prometheus/statefulset.yaml
  cluster/manifests/skipper/daemonset.yaml
Labels: ready-to-test

#1286 skipper update custom-routes change and OAuth tokeninfo request timeouts
  cluster/manifests/skipper/daemonset.yaml
Labels: ready-to-test

#1287 alpha-to-beta
  cluster/manifests/prometheus-node-exporter/daemonset.yaml
  cluster/manifests/prometheus/configmap.yaml
  cluster/manifests/prometheus/statefulset.yaml
  cluster/manifests/skipper/daemonset.yaml
Labels: ready-to-test

#1283 [dev] Pass VpcID to etcd stack
  cluster/etcd-cluster.yaml
Labels: do-not-merge

#1291 dev-to-alpha
  cluster/config-defaults.yaml
  cluster/manifests/skipper/daemonset.yaml
Labels: ready-to-test

#1295 Linking Cluster Lifecycle Manager
  README.rst
Labels: docs

#1294 alpha-to-beta
  cluster/config-defaults.yaml
  cluster/manifests/skipper/daemonset.yaml
Labels: ready-to-test

#1296 Add a simple spot termination handler
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1293 New etcd version
  cluster/etcd-cluster.yaml
Labels: ready-to-test

#1298 Reduce KUBE_MAX_PD_VOLS to support m5/c5 instances
  cluster/manifests/kube-cluster-autoscaler/deployment.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1300 Dev to alpha
  README.rst
  cluster/etcd-cluster.yaml
  cluster/manifests/emergency-access-service/deployment.yaml
  cluster/manifests/kube-cluster-autoscaler/deployment.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1309 Alpha to beta
  README.rst
  cluster/config-defaults.yaml
  cluster/etcd-cluster.yaml
  cluster/manifests/kube-cluster-autoscaler/deployment.yaml
  cluster/manifests/prometheus-node-exporter/daemonset.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1312 Remove Autobahn and Deployment Jenkins permissions after shutting them…
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1313 CA: Deployment -> DaemonSet
  cluster/manifests/deletions.yaml
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: ready-to-test

#1292 Run kube-downscaler in test clusters
  cluster/config-defaults.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
Labels: ready-to-test

#1315 fix go template: neq -> ne
  cluster/manifests/kube-downscaler/deployment.yaml
Labels: ready-to-test

#1316 Dev to alpha
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/emergency-access-service/ingress.yaml
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1314 decrease default CPU requests
  cluster/manifests/default-limits/limits.yaml
Labels: ready-to-test

#1318 fix memory leak in skipper, that is triggered by using tokeninfo filters
  cluster/manifests/skipper/daemonset.yaml
Labels: ready-to-test

#1319 alpha-to-beta
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/emergency-access-service/ingress.yaml
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1322 dev-to-alpha
  cluster/manifests/default-limits/limits.yaml
  cluster/manifests/skipper/daemonset.yaml
  prepare-pr.sh
Labels: ready-to-test

#1324 alpha-to-beta
  cluster/manifests/default-limits/limits.yaml
  cluster/manifests/skipper/daemonset.yaml
  prepare-pr.sh
Labels: ready-to-test

#1326 dev-to-kube-1.11
  cluster/manifests/default-limits/limits.yaml
  cluster/manifests/skipper/daemonset.yaml
  prepare-pr.sh
Labels: ready-to-test

#1330 SSH key and webhook changes.
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1328 Run kube-downscaler in production
  cluster/manifests/kube-downscaler/deployment.yaml
Labels: ready-to-test

#1331 dev-to-kube-1.11
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1329 Make all cluster wide HPA settings configurable
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1332 dev-to-alpha
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1335 Disable CFS quota
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1333 Settings for the new node drainer
  cluster/config-defaults.yaml
Labels: ready-to-test

#1337 Update 1.11 branch
  cluster/config-defaults.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1336 ExternalDNS v0.5.5
  cluster/manifests/external-dns/deployment.yaml
Labels: ready-to-test

#1344 dev-to-alpha
  cluster/config-defaults.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1347 Dev to kube 1.11
  cluster/config-defaults.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/prometheus-node-exporter/daemonset.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1348 Dev to alpha
  cluster/manifests/prometheus-node-exporter/daemonset.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1350 Alpha to beta
  cluster/config-defaults.yaml
  cluster/manifests/default-limits/limits.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/manifests/prometheus-node-exporter/daemonset.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
  prepare-pr.sh
Labels: ready-to-test

#1352 image-policy-webhook: update to v0.4.0
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test

#1354 Remove deprecated --allow-privileged kubelet flag
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: ready-to-test

#1355 Alpha to beta
  cluster/manifests/default-limits/limits.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
Labels: ready-to-test
