Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2019-04, with the labels that each got.

#1954 Update flannel-awaiter
  cluster/config-defaults.yaml
  cluster/manifests/flannel/daemonset.yaml
Labels: ready-to-test

#1957 dev-to-alpha
  cluster/config-defaults.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/heapster/deployment.yaml
  cluster/manifests/heapster/vpa.yaml
Labels: ready-to-test

#1958 beta-to-stable
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/ingress-template-controller/crd.yaml
  cluster/manifests/ingress-template-controller/deployment.yaml
Labels: ready-to-test

#1961 Update VPA to 0.4.0
  cluster/manifests/01-vertical-pod-autoscaler/01-crd.yaml
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
  cluster/manifests/external-dns/vpa.yaml
  cluster/manifests/heapster/vpa.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/vpa.yaml
  cluster/manifests/metrics-server/metrics-server-vpa.yaml
  cluster/manifests/prometheus/prometheus-vpa.yaml
Labels: do-not-merge, ready-to-test

#1956 feat: add role to write skipper config map (#1955)
  cluster/manifests/skipper/skipper-default-filter-writers.yaml
Labels: access-control, ready-to-merge, ready-to-test

#1960 feat:mount default filters ConfigMap for Skipper (#1959)
  cluster/manifests/skipper/deployment.yaml
Labels: ready-to-merge, ready-to-test

#1963 Update EAS
  cluster/manifests/emergency-access-service/deployment.yaml
Labels: ready-to-test

#1964 Alpha to beta
  cluster/config-defaults.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/heapster/deployment.yaml
  cluster/manifests/heapster/vpa.yaml
Labels: ready-to-test

#1966 feat: upgrade skipper to v0.10.200 (#1965)
  cluster/manifests/skipper/deployment.yaml
Labels: ready-to-test

#1968 Beta to stable
  cluster/config-defaults.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/heapster/deployment.yaml
  cluster/manifests/heapster/vpa.yaml
Labels: ready-to-test

#1975 dev-to-alpha
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/manifests/skipper/deployment.yaml
  delivery.yaml
Labels: ready-to-test

#1978 alpha-to-beta
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/manifests/skipper/deployment.yaml
  delivery.yaml
Labels: ready-to-test

#2009 Janitor cleanup rules: application label & CDP namespaces
  cluster/manifests/kube-janitor/deployment.yaml
  cluster/manifests/kube-janitor/rules-config.yaml
Labels: do-not-merge

#2038 Dev to kube 1.13
  cluster/manifests/kube-proxy/daemonset.yaml
  cluster/node-pools/master-default/userdata.clc.yaml
  cluster/node-pools/worker-default/userdata.clc.yaml
Labels: frozen
