Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2020-11, with the labels that each got.

#3715 spotio: use -XX:+ExitOnOutOfMemoryError
  cluster/manifests/spotio-controller/deployment.yaml
Labels: bugfix

#3717 fix skipper ep handling that is required to delete the service fallback
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/old_deployment.yaml
Labels: bugfix

#3733 [STABLE] Add option to switch to ELBv1 for APIServer
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
Labels: minor

#3750 fix: redis ratelimit used pipelines which are not safe to use
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/old_deployment.yaml
Labels: major

#3757 CA: increase the scaledown timeout
  cluster/config-defaults.yaml
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#3765 CA: add a workaround for TSC scaling issues
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#3771 CA: disable node instances cache (test only)
  cluster/config-defaults.yaml
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#3792 [STABLE] Set custom SG
  cluster/manifests/ingress-controller/deployment.yaml
Labels: bugfix
