Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2021-11, with the labels that each got.

#4767 Update admission-controller to master-132
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix, minor

#4773 Update cluster autoscaler
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix, minor

#4770 Enables `clusterRatelimit` group sharding
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/routesrv-deployment.yaml
Labels: major

#4784 Updates ingress controller
  cluster/manifests/ingress-controller/deployment.yaml
Labels: bugfix

#4791 Remove Kuberuntu v1.20 image
  cluster/config-defaults.yaml
Labels: minor
