Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2022-11, with the labels that each got.

#5504 Update Etcd AMI - enable `ethtool` and `processes` on Prometheus
  cluster/config-defaults.yaml
Labels: updates/etcd

#5470 Adding kubenurse
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/kubenurse/01-namespace.yaml
  cluster/manifests/kubenurse/daemonset.yaml
  cluster/manifests/kubenurse/ingress.yaml
  cluster/manifests/kubenurse/rbac.yaml
  cluster/manifests/kubenurse/service.yaml
  cluster/manifests/kubenurse/serviceaccount.yaml
  cluster/manifests/prometheus/configmap.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: in progress, experiment, do-not-merge

#5519 Remove outdated hostname_max_length config-item
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
Labels: do-not-merge

#5533 External dns mem config hotfix
  cluster/config-defaults.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/external-dns/vpa.yaml
Labels: minor
