Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2023-12, with the labels that each got.

#6596 fabric-gateway: make log level configurable
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#6600 Add mandatory pull request labels
  .zappr.yaml
Labels: documentation

#6599 Update kube-state-metrics to v2.10.1
  cluster/manifests/kube-state-metrics/deployment.yaml
Labels: minor

#6598 Update to node-exporter v1.7.0
  cluster/manifests/node-monitor/daemonset.yaml
Labels: minor

#6587 Enable CronJobTimeZone by default
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6606 Update admission-controller with configmap protection feature
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6610 Update GPU instance types for e2e
  test/e2e/cluster_config.sh
Labels: minor

#6611 Updates CLC to use policy v1 api
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
Labels: minor

#6607 Make nvidia device plugin ds run on Karpenter nodes
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#6592 skipper: enable manual canary deployment
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/hpa.yaml
Labels: architectural

#6616 Update AMI to use default value for max_user_watches
  cluster/config-defaults.yaml
Labels: minor

#6630 Update AMI, max_user_instances, nvidia driver
  cluster/config-defaults.yaml
Labels: major

#6636 Add missing fields description in the FabricGateway CRD
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#6635 Update to Prometheus v2.48.1
  cluster/manifests/prometheus/statefulset.yaml
Labels: minor

#6639 Avoid overwrite for deployment event resource
  _deploy_event/configmap.yaml
Labels: minor

#6625 ingress-controller: update to v0.14.34
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor, dependencies

#6593 Add kubelet-summary-metrics proxy
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/kubelet-summary-metrics/deployment.yaml
  cluster/manifests/kubelet-summary-metrics/hpa.yaml
  cluster/manifests/kubelet-summary-metrics/rbac.yaml
  cluster/manifests/kubelet-summary-metrics/service.yaml
  cluster/manifests/prometheus/configmap.yaml
Labels: minor

#6584 Add support for scaling on Nakadi metrics
  cluster/config-defaults.yaml
  cluster/manifests/kube-metrics-adapter/credentials.yaml
  cluster/manifests/kube-metrics-adapter/deployment.yaml
Labels: major

#6644 Also set UpdateReplacePolicy
  cluster/cluster.yaml
Labels: minor

#6643 ingress-controller: add application stack tag
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor

#6641 Set DeletionPolicy to retain for deplyoment secret kms key
  cluster/cluster.yaml
Labels: minor

#6642 Allow disabling deployment secret key management in cluster stack
  cluster/cluster.yaml
  cluster/config-defaults.yaml
Labels: minor

#6654 Increase CPU resources for kubelet-summary-proxy
  cluster/config-defaults.yaml
Labels: minor

#6664 Fix deployment event
  _deploy_event/configmap.yaml
  delivery.yaml
Labels: minor

#6561 Update to Karpenter v0.31.3
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/manifests/z-karpenter/karpenter.k8s.aws_awsnodetemplates.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#6665 Fix application association for deploy-event
  _deploy_event/configmap.yaml
  _deploy_event/stack.yaml
  delivery.yaml
Labels: minor

#6668 Only run kube2iam on worker nodes
  cluster/manifests/kube2iam/daemonset.yaml
Labels: minor

#6673 Only run ebs-csi-node on worker nodes
  cluster/manifests/03-ebs-csi/node.yaml
Labels: minor

#6661 Update StackSet controller to support traffic segments.
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/cluster_config.sh
  test/e2e/stackset/README.md
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: major

#6621 update: skipper after code freeze
  cluster/manifests/skipper/deployment.yaml
Labels: major

#6680 Revert "Only run kube2iam on worker nodes"
  cluster/manifests/kube2iam/daemonset.yaml
Labels: bugfix

#6676 Pass region to karpenter
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#6678 Update aws-encryption-provider to latest version
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6675 Update audittrail-adapter version
  cluster/manifests/audittrail-adapter/daemonset.yaml
Labels: minor

#6670 Fix reference to deploy key
  cluster/cluster.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: bugfix, minor

#6686 Only use alias when key centrally managed
  cluster/manifests/deployment-service/controller-statefulset.yaml
Labels: bugfix

#6679 skipper-ingress: enable canary deployment by default
  cluster/config-defaults.yaml
Labels: major

#6689 Update to flannel v0.24.0
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#6691 Add field for controlling traffic segment enablement.
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#6690 Add ephemeral storage limit to etcd-backup job
  cluster/manifests/etcd-backup/cronjob.yaml
Labels: minor

#6692 Control traffic segment feature in deployment-service
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#6684 update: skipper-ingress cwfreeze 2nd step 2/2
  cluster/manifests/skipper/deployment.yaml
  test/e2e/routegroup.go
Labels: major

#6698 Update Audittrail Adapter version
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/audittrail-adapter/daemonset.yaml
Labels: architectural

#6705 Update skipper-ingress to deploy lock-free endpointregistry
  cluster/manifests/skipper/deployment.yaml
Labels: minor
