Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-12, with the labels that each got.

#8548 adding a special instance-types string 'not-specified'
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#8551 Add an admitter that validates that unprivileged users cannot exec into postgres pods
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/teapot.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#8577 Exclude kubenurse from being considered for a node to get ready
  cluster/manifests/kubenurse/daemonset.yaml
Labels: minor

#8604 skipper-internal: Update main fleet to version v0.21.224-1047
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#8608 add appropriate RBAC for the role-sync-controller
  cluster/manifests/deletions.yaml
  cluster/manifests/role-sync-controller/rbac.yaml
  test/e2e/authorization.go
Labels: minor

#8588 Enable previously disabled e2e tests for authz
  test/e2e/run_e2e.sh
Labels: minor

#8626 dev to eks
  cluster/manifests/01-coredns-local/daemonset-coredns.yaml
  cluster/manifests/04-ebs-csi/node.yaml
  cluster/manifests/kubenurse/prometheus.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: frozen, minor

#8633 Update dcgm-exporter to 3.3.9-3.6.1 release
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#8651 skipper: Fix formatting of flags
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#8659 Add test suite that covers auth-related admission checks
  cluster/cluster.yaml
  cluster/manifests/02-admission-control/deployment.yaml
  cluster/manifests/02-admission-control/teapot.yaml
  delivery.yaml
  test/e2e/authorization.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: minor
