Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-02, with the labels that each got.

#6878 Update skipper version to catch up some small changes, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#6887 Exclude c5d.large from default Karpenter instance-types
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#6888 skipper: update canary version to v0.19.40
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#6893 Update Stackset controller with Stack owned Secrets feature
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  cluster/manifests/stackset-controller/rbac.yaml
Labels: minor

#6895 Update StackSet controller end-2-end flags.
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/deployment.yaml
Labels: minor

#6899 skipper: update canary to v0.19.44
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#6898 add feature gate MaxUnavailableStatefulSet
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6892 Containerd update
  cluster/config-defaults.yaml
Labels: minor

#6903 skipper: update hostname-credentials-controller to main-11
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#6902 fabric-gateway: update to master-237
  cluster/config-defaults.yaml
Labels: minor

#6915 skipper: update main version to v0.19.44
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#6852 Karpenter update
  cluster/cluster.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/z-karpenter/01-rbac.yaml
  cluster/manifests/z-karpenter/01-serviceaccount.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/03-rolebinding.yaml
  cluster/manifests/z-karpenter/04-clusterrole.yaml
  cluster/manifests/z-karpenter/05-clusterrole-core.yaml
  cluster/manifests/z-karpenter/06-aggregate-clusterrole.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/configmap.yaml
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/manifests/z-karpenter/karpenter.sh_machines.yaml
  cluster/manifests/z-karpenter/karpenter.sh_provisioners.yaml
  cluster/manifests/z-karpenter/poddisruptionbudget.yaml
  cluster/manifests/z-karpenter/service.yaml
  cluster/manifests/z-karpenter/webhooks.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#6923 Update VPA CRD
  cluster/manifests/01-vertical-pod-autoscaler/01-crd.yaml
  cluster/manifests/02-kube-aws-iam-controller/vpa.yaml
  cluster/manifests/03-ebs-csi/vpa.yaml
  cluster/manifests/cronjob-fixer/vpa.yaml
  cluster/manifests/deployment-service/status-service-vpa.yaml
  cluster/manifests/external-dns/vpa.yaml
  cluster/manifests/ingress-controller/vpa.yaml
  cluster/manifests/kube-downscaler/vpa.yaml
  cluster/manifests/kube-janitor/vpa.yaml
  cluster/manifests/kube-metrics-adapter/vpa.yaml
  cluster/manifests/kube-state-metrics/vpa.yaml
  cluster/manifests/kubenurse/prometheus.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/vpa.yaml
  cluster/manifests/metrics-server/metrics-server-vpa.yaml
  cluster/manifests/pdb-controller/vpa.yaml
  cluster/manifests/prometheus/prometheus-vpa.yaml
  cluster/manifests/stackset-controller/vpa.yaml
  cluster/manifests/z-karpenter/vpa.yaml
Labels: minor

#6927 fix karpenter ServiceAccount
  cluster/manifests/z-karpenter/01-serviceaccount.yaml
Labels: bugfix

#6929 Enable traffic segment probing when cluster supports either annotated segments or segments by default.
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#6938 Enable versioned configuration resources support for test environments
  cluster/config-defaults.yaml
Labels: minor

#6942 [MANUAL] Beta to stable
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/psp/pod_security_policy.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/admission_controller.go
  test/e2e/apiserver.go
  test/e2e/audit.go
  test/e2e/authorisation_test.go
  test/e2e/aws_iam.go
  test/e2e/external_dns.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/gpu.go
  test/e2e/infra.go
  test/e2e/ingress.go
  test/e2e/kube_metrics_adapter_test.go
  test/e2e/node_test.go
  test/e2e/psp.go
  test/e2e/routegroup.go
  test/e2e/run_e2e.sh
  test/e2e/util.go
Labels: frozen, major

#6065 Update to Kubernetes v1.25
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/psp/pod_security_policy.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/admission_controller.go
  test/e2e/apiserver.go
  test/e2e/audit.go
  test/e2e/authorisation_test.go
  test/e2e/aws_iam.go
  test/e2e/external_dns.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/gpu.go
  test/e2e/infra.go
  test/e2e/ingress.go
  test/e2e/kube_metrics_adapter_test.go
  test/e2e/node_test.go
  test/e2e/psp.go
  test/e2e/routegroup.go
  test/e2e/run_e2e.sh
  test/e2e/util.go
Labels: major

#6944 lower karpenter resource thresholds
  cluster/config-defaults.yaml
Labels: minor

#6945 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: major

#6931 Scale master node Daemonset VPAs dynamically relative to master node size
  cluster/config-defaults.yaml
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
  cluster/manifests/02-kube-aws-iam-controller/vpa.yaml
  cluster/manifests/03-ebs-csi/controller.yaml
  cluster/manifests/03-ebs-csi/vpa.yaml
  cluster/manifests/z-karpenter/vpa.yaml
Labels: minor

#6963 skipper: fix redis service port
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#6960 Add MaxUnavailableStatefulSet feature flag to controller-manager
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6967 Update StackSet Controller
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#6946 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: major

#6964 feature: allow to disable cross zone balancing
  cluster/config-defaults.yaml
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor

#6968 Update components to use Kubernetes v1.25 client libraries
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
  cluster/manifests/kube-metrics-adapter/deployment.yaml
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
  cluster/manifests/kube-node-ready/daemonset.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: dependencies

#6969 Update to unbound 1.19.1
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: minor

#6975 Bump StackSet Controller version.
  cluster/manifests/stackset-controller/deployment.yaml
  delivery.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: bugfix

#6578 update cadvisor path to containerd
  cluster/manifests/node-monitor/daemonset.yaml
Labels: minor

#6979 Fix runtime policy injection for prod
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#6985 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major

#6991 Revert "Fix runtime policy injection for prod"
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#6995 Update StackSet Controller version.
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: bugfix

#6996 Give karpenter more memory by default
  cluster/config-defaults.yaml
  cluster/manifests/z-karpenter/vpa.yaml
Labels: minor

#6999 skipper: do not use service account with routesrv
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7005 Fix focal v1.26 amd64 AMI
  cluster/config-defaults.yaml
Labels: bugfix

#7003 skipper: configure terminationMessagePolicy
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7011 Update stackset-controller to v1.4.39
  cluster/manifests/stackset-controller/deployment.yaml
Labels: minor

#7012 deployment-service: Update deps
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: dependencies

#6986 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major

#7007 feature: skipper-ingress redis hpa configure scale-down behavior
  cluster/config-defaults.yaml
  cluster/manifests/skipper/hpa-redis.yaml
Labels: minor

#6998 Fix runtime policy handling
  cluster/manifests/01-admission-control/config.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#7014 Modernize instance types in e2e
  test/e2e/cluster_config.sh
Labels: minor

#7022 Configure dependabot for skipper
  .github/dependabot.yml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
  cluster/manifests/skipper/secret-combiner.yaml
Labels: dependencies

#7015 skipper: update canary to v0.20.14
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major

#7026 skipper: update version to v0.20.15
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7021 fabric: update version to master-240
  cluster/config-defaults.yaml
Labels: minor, dependencies

#7028 Update unbound telemetry image
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: minor

#7032 Reduce ephemeral storage default
  cluster/config-defaults.yaml
Labels: minor

#7036 Add admission for ephemeralcontainers
  cluster/manifests/01-admission-control/teapot.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7037 use distroless container build for skipper-ingress
  cluster/manifests/skipper/deployment.yaml
Labels: major

#7044 optimize: promql query route separation
  cluster/manifests/prometheus/configmap.yaml
Labels: minor

#7040 Cloud controller log annotation
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: minor

#7048 Update Admission Controller.
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7034 Update to Karpenter v0.34.1
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#7053 stackset: Fix HPA e2e test for all Kubernetes versions
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: bugfix

#7052 Update skipper main fleet version
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major

#7065 Make nvidia device plugin resources configurable
  cluster/config-defaults.yaml
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#7067 Tag Network Interfaces with application/component
  cluster/etcd/stack.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#7066 [BETA] Kubernetes v1.26
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/manifests/aws-cloud-controller-manager/rbac.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/audit.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/util.go
Labels: do-not-merge, major

#7070 Fix calculating karpenter vpa max CPU
  cluster/manifests/z-karpenter/vpa.yaml
Labels: minor

#7063 Update skipper version, step 1/2
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#7074 Disable kube-node-ready on master nodes in test
  cluster/config-defaults.yaml
Labels: minor

#7086 Don't make resource tagging depending on Jammy
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: major

#6854 skipper: use redis 7
  cluster/manifests/skipper/skipper-redis.yaml
Labels: major

#7083 Disable kube2iam on master nodes in test
  cluster/config-defaults.yaml
  cluster/manifests/kube2iam/daemonset.yaml
Labels: minor

#7084 Update to CoreDNS v1.11.2
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: minor

#7085 Update to Prometheus v2.50.1
  cluster/manifests/prometheus/statefulset.yaml
Labels: minor

#7093 Limit number of pods per node for Karpenter nodes
  cluster/config-defaults.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#7095 Use hostNetwork for EC2 metadata access for aws-cloud-controller-manager
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: minor

#7094 Update StackSet Controller version.
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7101 [ALPHA] Use hostnetwork for aws-cloud-controller-manager to access ec2 metadata
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: bugfix

#7104 Fix condition for maxPods
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix

#7102 Update to nvidia-device-plugin v0.14.5
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor
