Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-04, with the labels that each got.

#7230 Update VPA CRD for vpa 1.0.0
  cluster/manifests/01-vertical-pod-autoscaler/01-crd.yaml
Labels: bugfix

#7232 Allow vpa-updater to delete pods
  cluster/manifests/01-vertical-pod-autoscaler/rbac.yaml
Labels: bugfix

#7236 skipper: replace parent-resource-hash selector
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/skipper-redis.yaml
Labels: minor

#7242 skipper: require unique hosts in RouteGroup CRD
  cluster/manifests/01-routegroup/routegroup-crd.yaml
Labels: minor

#7238 Update to Karpenter v0.35.4
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#7246 fabric: update to master-247
  cluster/config-defaults.yaml
Labels: dependencies

#7245 Update deployment-service version.
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7253 Allow zmon-worker to access airflow ressources
  cluster/cluster.yaml
Labels: minor

#7249 Disable kube-node-ready on master nodes
  cluster/config-defaults.yaml
Labels: minor

#7255 skipper: go update to go1.22.2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7248 rename configmap in config-provider-service rbac
  cluster/manifests/roles/config-provider-rbac.yaml
Labels: minor

#7267 Document the open_sg_ingress_ranges config-item
  cluster/config-defaults.yaml
Labels: documentation

#7260 skipper: go update to go1.22.2 - step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7270 Disable kube2iam on master nodes in production
  cluster/config-defaults.yaml
Labels: minor

#7275 e2e: Make decomission step more graceful
  test/e2e/run_e2e.sh
Labels: bugfix

#7279 skipper: update dependencies and prepare poc
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/secret.yaml
Labels: minor

#7261 Remove traffic segment config items.
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/01-config.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7285 skipper: update dependencies and lua script feature for poc
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7294 Update deployment service version.
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7305 remove okta_auth_enabled config item because it's enabled by default
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/roles/cluster-admin-binding.yaml
  cluster/manifests/roles/collaborator-roles.yaml
  cluster/manifests/roles/poweruser-binding.yaml
  cluster/manifests/roles/readonly-binding.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7304 Enable Stack versioned PCS for Stackset
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
Labels: minor

#7298 Add ClusterRole and ClusterRoleBinding for deployment-service-executor User
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/controller-rbac.yaml
Labels: minor

#7310 Update StackSet controller version.
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7297 stackset: update CRDs
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
Labels: major

#7317 stackset: update CRDs (followup)
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
Labels: minor

#7006 Update to Kubernetes v1.28
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  test/e2e/Makefile
  test/e2e/apiserver.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: do-not-merge, major

#7326 adding permissions to create/update platformcredentialsset by cdp
  cluster/manifests/roles/cdp-controller-rbac.yaml
Labels: minor

#7329 PCS: set preserveUnknownFields=false for all clusters
  cluster/manifests/01-platformcredentialsset/customresourcedefinition.yaml
Labels: major

#7319 Update prometheus version used during loadtest
  test/e2e/loadtest/client/prom-statefulset.yaml
Labels: minor

#7325 Update components to kube 1.28 [1/N]
  cluster/manifests/03-ebs-csi/controller.yaml
  cluster/manifests/03-ebs-csi/node.yaml
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/event-logger/statefulset.yaml
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/pdb-controller/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7324 Update kube-static-egress-controller to Kubernetes v1.28
  cluster/manifests/kube-static-egress-controller/deployment.yaml
Labels: minor

#7340 Update components to kube 1.28 [2/2]
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
  cluster/manifests/ingress-controller/deployment.yaml
  cluster/manifests/kube-metrics-adapter/deployment.yaml
Labels: minor

#7347 Bump version of deployment service components.
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7346 Update to Kubernetes v1.29.4
  cluster/config-defaults.yaml
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: major

#7343 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major

#7349 skipper: setup lua environment for operators
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7360 Clean up Skipper Passive Health Check (PHC) configuration
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7362 Zmon role can list tags for IAM certificates
  cluster/cluster.yaml
Labels: access-control, minor

#7368 Fix VPA limit for ebs-csi-controller
  cluster/manifests/03-ebs-csi/vpa.yaml
Labels: bugfix

#7372 e2e: enable access via Okta
  test/e2e/cluster_config.sh
Labels: minor

#7375 fabric: update to master-250
  cluster/config-defaults.yaml
Labels: dependencies

#7376 Increase timeout for gpu e2e test
  test/e2e/gpu.go
Labels: bugfix

#7374 Make jammy the default for worker nodes
  cluster/config-defaults.yaml
Labels: minor

#7381 skipper: update main version to v0.21.62
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7387 Update stackset controller
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7393 Update base image used by etcd-backup
  cluster/manifests/etcd-backup/cronjob.yaml
Labels: dependencies

#7394 Update the base image of journald-reader
  cluster/manifests/node-monitor/daemonset.yaml
Labels: dependencies

#7388 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7402 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#7024 Update to Kubernetes v1.29
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/external_dns.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/gpu.go
  test/e2e/node_test.go
Labels: do-not-merge, major

#7407 Make etcd DNS record configurable
  cluster/config-defaults.yaml
  cluster/etcd/stack.yaml
  test/e2e/cluster_config.sh
Labels: major

#7414 Update tokeninfo
  cluster/node-pools/master-default/userdata.yaml
Labels: dependencies

#7389 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor
