Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-05, with the labels that each got.

#7416 Components v1.29 [1/X]
  cluster/manifests/03-ebs-csi/controller.yaml
  cluster/manifests/03-ebs-csi/node.yaml
  cluster/manifests/kube-static-egress-controller/deployment.yaml
  cluster/manifests/pdb-controller/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7419 skipper: update image to use amazonlinux base image (step 1/2)
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#7426 Update components to kubernetes 1.29
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
  cluster/manifests/stackset-controller/deployment.yaml
Labels: minor

#7428 bump karpenter version
  cluster/manifests/z-karpenter/deployment.yaml
Labels: bugfix

#7422 feature: enable to switch nlb zone affinity
  cluster/config-defaults.yaml
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor

#7430 fabric: update to master-251
  cluster/config-defaults.yaml
Labels: architectural

#7437 Introduce separate config item for pod factory configmap deletion protection
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7421 Add support for additional cluster regions
  cluster/etcd/stack.yaml
  cluster/manifests/kube-metrics-adapter/deployment.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: major

#7451 Update to flannel v0.25.1
  cluster/manifests/coredns-local/daemonset-coredns.yaml
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#7454 Update VPA to v1.1.1
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
Labels: minor

#7457 Update aws-node-decommissioner
  cluster/manifests/aws-node-decommissioner/cronjob.yaml
Labels: dependencies

#7458 Update to etcd v3.5.13
  cluster/config-defaults.yaml
  cluster/manifests/etcd-backup/cronjob.yaml
Labels: major

#7467 skipper: update canary to v0.21.86
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#7462 Update to CoreDNS v1.11.3
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: minor

#7473 Add 7i instances as default option in Karpenter
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: major

#7471 skipper: update hostname-credentials-controller to main-13
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: architectural, dependencies

#7474 Remove Kubernetes-on-Ubuntu v1.28 images
  cluster/config-defaults.yaml
Labels: do-not-merge, minor

#7482 skipper: update main fleet to v0.21.86
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#7484 Remove focal AMI no longer used
  cluster/config-defaults.yaml
Labels: major

#7493 ingress-controller: update image to base amazonlinux
  cluster/manifests/ingress-controller/deployment.yaml
Labels: do-not-merge, architectural

#7500 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#7502 chore(deps): update kubernetes-lifecycle-metrics, kube-node-ready-controller
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
Labels: do-not-merge, dependencies

#7504 prometheus: cleanup ingress
  cluster/manifests/deletions.yaml
  cluster/manifests/prometheus/ingress.yaml
Labels: minor

#7509 deployment-service: support multiple clusters per account [1/2]
  cluster/manifests/deployment-service/status-service-ingress.yaml
Labels: major

#7518 Update deployment-service with support for cleanup seconds
  cluster/manifests/deployment-service/00-crd.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7501 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#7525 Update to Kubernetes v1.30.1
  cluster/config-defaults.yaml
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: major

#7523 Fix deployment-status-service dns name length issue
  cluster/manifests/deployment-service/status-service-ingress.yaml
Labels: bugfix

#7476 update karpenter version
  cluster/manifests/z-karpenter/deployment.yaml
Labels: major

#7522 Update admission-controller to master-204
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7533 Update VPA to v1.1.2
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
Labels: minor

#7532 Remove configuration for renovate bot
  renovate.json
Labels: minor

#7539 skipper: update version (step 1/2)
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#7541 Update `stackset-controller` and its tests to `v1.4.75`
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7540 Update aws-cloud-controller manager to v1.30
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: major

#7545 Patch kube-scheduler to fix crash
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#7511 deployment-service: use new status-service url [2/2]
  cluster/manifests/deployment-service/01-config.yaml
Labels: major

#7555 Revert "use slimmer version from amazon-linux"
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7557 skipper: add hostname-credentials-controller version labels
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#7561 Drop old deploy-service-status [3/3]
  cluster/manifests/deployment-service/status-service-ingress.yaml
Labels: minor

#7562 Add NVIDIA's `dcgm-exporter` to export GPU metrics to Prometheus
  cluster/config-defaults.yaml
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#7565 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: architectural, dependencies

#7569 Update components to Static base image [1/X]
  cluster/manifests/audittrail-adapter/daemonset.yaml
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/cronjob-fixer/deployment.yaml
  cluster/manifests/event-logger/statefulset.yaml
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
  cluster/manifests/kube-node-ready/daemonset.yaml
  cluster/manifests/kubelet-summary-metrics/deployment.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/spot-node-rescheduler/cronjob.yaml
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: major

#7573 Update admission-controller to master-206
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7576 Update to karpenter v0.36.2
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#7544 deployment-service: restrict access to healthcheck endpoint
  cluster/manifests/deletions.yaml
  cluster/manifests/deployment-service/status-service-ingress.yaml
Labels: minor

#7566 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: architectural, dependencies

#7584 Update base images of several applications to amazonlinux or static
  cluster/manifests/coredns-local/daemonset-coredns.yaml
  cluster/manifests/etcd-backup/cronjob.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/node-monitor/daemonset.yaml
  test/e2e/loadtest/client/loadtest-deployment.yaml
  test/e2e/util.go
Labels: minor

#7585 Update emergency-access-service to static base image
  cluster/manifests/emergency-access-service/deployment.yaml
Labels: minor

#7589 Update etcd-proxy to use static base image
  cluster/manifests/emergency-access-service/deployment.yaml
Labels: minor

#7595 Update and revert broken Dockerfiles to working versions
  cluster/manifests/etcd-backup/cronjob.yaml
  cluster/manifests/node-monitor/daemonset.yaml
Labels: bugfix

#7599 Revert "Update etcd-proxy to use static base image"
  cluster/manifests/emergency-access-service/deployment.yaml
Labels: bugfix

#7602 Update etcd-proxy base image
  cluster/manifests/emergency-access-service/deployment.yaml
Labels: minor

#7608 Update to flannel v0.25.2
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#7604 Update stackset-controller and its tests to v1.4.76
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7607 skipper: use amazonlinux slim again but with `curl` (step 1/2)
  cluster/manifests/skipper/deployment.yaml
Labels: architectural
