Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-08, with the labels that each got.

#7918 Update fabric-gateway-controller
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#7921 Use `-enable-versioning=true` instead of `-enable-versioning`
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#7924 Add fabric-gateway-controller snapshotting support
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#7930 Update fabric-gateway-controller
  cluster/manifests/fabric-gateway/01-rbac.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#7933 Update fabric-gateway-controller
  cluster/manifests/fabric-gateway/01-rbac.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: major

#7934 Update RBAC to correspond to fabric-gateway-controller code
  cluster/manifests/fabric-gateway/01-rbac.yaml
Labels: minor

#7938 Update RBAC to correspond to fabric-gateway-controller code
  cluster/manifests/fabric-gateway/01-rbac.yaml
Labels: minor

#7940 Update fabric-gateway-controller
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: major

#7941 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, dependencies

#7945 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, dependencies

#7916 Add Session Manager logging CF
  cluster/cluster.yaml
  delivery.yaml
  test/e2e/apply/secret.yaml
  test/e2e/cluster_config.sh
Labels: minor

#7952 Add region condition to SSM session logging
  cluster/cluster.yaml
Labels: minor

#7960 Make Session Manager logging resources unique per cluster
  cluster/cluster.yaml
Labels: bugfix

#7966 Update cluster.yaml
  cluster/cluster.yaml
Labels: bugfix

#7967 [CHERRYPICK] Set infrastructure tag to Falso in SSM document.
  cluster/cluster.yaml
Labels: bugfix

#7969 [CHERRYPICK] Set infrastructure tag to Falso in SSM document.
  cluster/cluster.yaml
Labels: bugfix

#7972 [CHERRYPICK] Set infrastructure tag to Falso in SSM document.
  cluster/cluster.yaml
Labels: bugfix

#7973 [e2e] add kube-system as soft fail namespace in admission-controller pod admitter
  test/e2e/cluster_config.sh
Labels: minor

#7974 update: skipper step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7975 deploy: pod deletion cost controller
  cluster/manifests/skipper/01-rbac-pod-deletion-cost-controller.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#7979 fix: pod-deletion-cost-controller use also patch under the hood
  cluster/manifests/skipper/01-rbac-pod-deletion-cost-controller.yaml
Labels: bugfix

#7976 fix: missing image label that we need for versioned metrics
  cluster/manifests/prometheus/configmap.yaml
Labels: bugfix

#7964 reduce the disruption budget of the karpenter node pools node pools
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#7983 update: skipper step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7982 [e2e] replace deprecated k8s registry with the new one for e2e images
  test/e2e/admission_controller.go
  test/e2e/util.go
Labels: minor

#7981 Improve code quality for e2e tests by fixing linter errors
  test/e2e/admission_controller.go
  test/e2e/authorisation_test.go
  test/e2e/gpu.go
  test/e2e/ingress.go
  test/e2e/kube_metrics_adapter_test.go
  test/e2e/node_test.go
  test/e2e/routegroup.go
  test/e2e/util.go
Labels: minor

#7995 configurable memory for cost_controller pods
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#7996 Cost controller memory
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#7998 Cost controller memory
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#8000 configurable memory for cost_controller pods
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#7993 Update fabric-gateway-controller
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: bugfix, dependencies

#8001 config: pod-deletion-cost-controller
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#8009 double the memory of karpenter controller
  cluster/manifests/z-karpenter/vpa.yaml
Labels: minor

#8014 [e2e] use framework.ExpectNoError for assertions
  test/e2e/README.md
  test/e2e/admission_controller.go
  test/e2e/apiserver.go
  test/e2e/authorisation_test.go
  test/e2e/aws_iam.go
  test/e2e/external_dns.go
  test/e2e/infra.go
  test/e2e/ingress.go
  test/e2e/kube_metrics_adapter_test.go
  test/e2e/psp.go
  test/e2e/routegroup.go
  test/e2e/util.go
Labels: enhancement, minor

#8016 [e2e] use bigger instance for `default-worker-splitaz` to avoid flake
  test/e2e/cluster_config.sh
Labels: bugfix, e2e

#8019 [e2e] re-enable skipped e2e tests
  cluster/config-defaults.yaml
  test/e2e/routegroup.go
  test/e2e/run_e2e.sh
Labels: minor, e2e
