Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-07, with the labels that each got.

#7642 `journald-reader`: mount `/usr` to access `libsystemd` and `python`
  cluster/manifests/node-monitor/daemonset.yaml
Labels: minor

#7769 skipper: add config item for default authentication filters
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7771 Update to node-exporter 1.8.1
  cluster/manifests/node-monitor/daemonset.yaml
Labels: minor

#7772 Update to flannel v0.25.4
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#7775 Kubernetes v1.30.2 components [3/X]
  cluster/manifests/audittrail-adapter/daemonset.yaml
  cluster/manifests/cronjob-fixer/deployment.yaml
  cluster/manifests/event-logger/statefulset.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/kubelet-summary-metrics/deployment.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/spot-node-rescheduler/cronjob.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: dependencies

#7773 Update aws-cloud-controller-manager to v1.30.2
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: minor

#7774 Update to Prometheus v2.53.0
  cluster/manifests/prometheus/statefulset.yaml
Labels: minor

#7776 Update to kube-state-metrics v2.12.0
  cluster/manifests/kube-state-metrics/deployment.yaml
Labels: minor

#7786 skipper: update canary to v0.21.139
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, dependencies

#7787 Update ExternalDNS to v0.14.2
  cluster/manifests/external-dns/deployment.yaml
Labels: dependencies

#7792 update deployment-service deps for k8s v1.30
  cluster/manifests/deployment-service/00-crd.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7795 Update kube-node-ready-controller dependencies to Kubernetes v1.30
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
Labels: dependencies

#7796 fabric: enable on all clusters by default
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
  cluster/manifests/kube-janitor/rules-config.yaml
Labels: minor

#7798 Update preStop hooks
  cluster/manifests/skipper/skipper-redis.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7803 Update stackset CRDs to Kubernetes v1.30
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
Labels: minor

#6669 Force imdsv2 (master nodes)
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
Labels: major

#7804 update deployment-service and add the new CRD
  cluster/manifests/deployment-service/00-crd-cleanup-task.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: architectural

#7805 eks: Use known ipv4 service CIDR range
  cluster/cluster.yaml
  cluster/manifests/01-aws-node/01-sa.yaml
  cluster/manifests/01-aws-node/daemonset.yaml
Labels: minor

#7810 EKS branch cleanup
  cluster/config-defaults.yaml
  cluster/manifests/01-coredns-local/service-coredns.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/skipper/service-internal.yaml
Labels: minor

#7675 skipper: remove deprecated enable_skipper_eastwest config
  cluster/config-defaults.yaml
  cluster/manifests/coredns-local/configmap-local.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7813 fix: skipper build go version 1.22.5
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7822 update deployment-service with resource cleanup task handler
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7827 Give deployment-service permission to handle resource cleanup tasks
  cluster/manifests/deployment-service/controller-rbac.yaml
  cluster/manifests/roles/deployment-service.yaml
Labels: bugfix

#7825 update kube-node-ready-controller
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
Labels: minor

#7832 kube-aws-iam-controller: Don't assume worker role on eks
  cluster/manifests/03-kube-aws-iam-controller/deployment.yaml
Labels: minor

#7831 fix: skipper fleet to use Go version 1.22.5
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7833 Update CDPResourceCleanupTask resource to the latest spec
  cluster/manifests/deployment-service/00-crd-cleanup-task.yaml
Labels: minor

#7834 Update to Prometheus v2.53.1
  cluster/manifests/prometheus/statefulset.yaml
Labels: minor

#7837 Disable ssh by default
  cluster/config-defaults.yaml
Labels: minor

#7843 Use static base image for more components
  cluster/manifests/kube-static-egress-controller/deployment.yaml
  cluster/manifests/pdb-controller/deployment.yaml
Labels: minor

#7842 Update tokeninfo base image to use static base image
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7845 Use static base image for VPA components
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
Labels: minor

#7847 Update deployment-service to expose resource status
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7849 Update encryption-provider to use static base image
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7841 Include alias in Prometheus endpoint
  cluster/manifests/prometheus/ingress.yaml
Labels: bugfix

#7854 fix: skipper unset endpointslices
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7860 fix: skipper unset endpointslices step2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7885 fabric: update crd
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#7891 skipper: update canary to v0.21.161
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#7894 Configure flannel-awaiter requests.
  cluster/config-defaults.yaml
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#7903 skipper: update main fleet to v0.21.161
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#7818 eks: PoC: Zalando IAM AWS Proxy
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/controller-rbac.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/zalando-iam-aws-proxy/deployment.yaml
  cluster/manifests/zalando-iam-aws-proxy/hpa.yaml
  cluster/manifests/zalando-iam-aws-proxy/rbac.yaml
  cluster/manifests/zalando-iam-aws-proxy/routegroup.yaml
  cluster/manifests/zalando-iam-aws-proxy/service.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
Labels: minor
