Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-09, with the labels that each got.

#8023 fix: pod deletion by fixing deadlock in data structure
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: bugfix

#8024 Add retention policies to the SSM-SessionManagerRunShell Document
  cluster/cluster.yaml
Labels: minor

#8020 add exception handling in toggle-scaledown.py
  test/e2e/run_e2e.sh
  test/e2e/toggle-scaledown.py
Labels: enhancement, minor

#8034 [e2] refactor external-dns test to use `service.TestJig`
  test/e2e/external_dns.go
  test/e2e/util.go
Labels: minor

#8008 Create SSM Documents per Cluster
  cluster/cluster.yaml
Labels: minor

#8045 introduce config-items to control kubelet image qps
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
Labels: enhancement, minor

#8049 feature: allow new filter tracingTagFromResponseIfStatus
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#8052 feature: pdcc optional resync
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
Labels: minor

#8056 Update fabric-gateway-controller
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: bugfix

#8062 update dependencies in loadtest-e2e
  test/e2e/loadtest/client/loadtest-deployment.yaml
  test/e2e/loadtest/client/prom-statefulset.yaml
Labels: minor

#8067 update: skipper opa improvements
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#8071 Update deployment-service to expose PCS resource status
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: bugfix

#8072 update stackset-e2e
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#8079 config: skipper redis connections
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#8075 [e2e] minor improvements to build
  delivery.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
Labels: enhancement, minor, e2e

#8073 update: skipper opa improvements [2/2]
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#8081 use patched flannel-awaiter
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#8094 Remove region conditional for SSM resource creation
  cluster/cluster.yaml
Labels: minor

#8092 [1/2] remove k8s dashboard resources
  cluster/config-defaults.yaml
  cluster/manifests/dashboard/deployment.yaml
  cluster/manifests/dashboard/rbac.yaml
  cluster/manifests/dashboard/scraper-vpa.yaml
  cluster/manifests/dashboard/scraper.yaml
  cluster/manifests/dashboard/service.yaml
  cluster/manifests/deletions.yaml
Labels: major

#8099 [e2e] skip flakey gradual traffic routes test
  test/e2e/run_e2e.sh
Labels: minor

#8105 [2/2] remove k8s dashboard resources
  cluster/manifests/deletions.yaml
Labels: minor

#8121 update aws-cloud-controller-manager to 1.31.0
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: bugfix

#8124 [hotfix-stable] update aws-cloud-controller-manager to 1.31.0
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
Labels: bugfix

#8140 Allow Powerusers to patch pods/ephemeralcontainers
  cluster/manifests/roles/poweruser-role.yaml
Labels: minor

#8134 canary-controller: add manifests
  cluster/config-defaults.yaml
  cluster/manifests/skipper-canary-controller/01-canary-service-account.yaml
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: minor

#8151 skipper,fabric-gateway: enable image-updater-bot
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#8150 clean up minor k8s 1.30 references
  cluster/config-defaults.yaml
Labels: minor

#8149 Dev to eks [manual]
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/manifests/skipper-canary-controller/01-canary-service-account.yaml
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  test/e2e/Makefile
  test/e2e/apiserver.go
  test/e2e/audit.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/node_test.go
  test/e2e/util.go
Labels: major

#8166 canary-controller: fix cronjob validation
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: bugfix

#8167 Dev to eks [manual]
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#8171 canary-controller: inject rest of Otel vars
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: bugfix, minor

#8182 Update VPA components to v1.2.1
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
Labels: minor

#8183 update: skipper OPA URL query policy, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#8186 ingress: log into both cluster and infra accounts
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
  cluster/manifests/skipper/skipper-redis.yaml
Labels: major

#8184 fix: canary controller cronjob name
  cluster/manifests/deletions.yaml
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: minor

#8196 Dev to eks [manual]
  cluster/manifests/02-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/02-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/02-vertical-pod-autoscaler/updater-deployment.yaml
  cluster/manifests/03-kube-aws-iam-controller/deployment.yaml
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/cronjob-fixer/deployment.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/emergency-access-service/deployment.yaml
  cluster/manifests/event-logger/statefulset.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
  cluster/manifests/kubelet-summary-metrics/deployment.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
  cluster/manifests/skipper/pod-deletion-cost-controller.yaml
  cluster/manifests/skipper/skipper-redis.yaml
  cluster/manifests/spot-node-rescheduler/cronjob.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#8193 skipper: automate canary version update
  cluster/manifests/skipper/deployment.yaml
Labels: major

#8200 skipper-canary: update logs destination
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: minor

#8206 skipper-canary: fix cronjob annotations identation
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: bugfix

#8172 clean up the k8s dashboard completely
  README.rst
  cluster/config-defaults.yaml
  cluster/manifests/dashboard/deployment.yaml
  cluster/manifests/dashboard/rbac.yaml
  cluster/manifests/dashboard/scraper-vpa.yaml
  cluster/manifests/dashboard/scraper.yaml
  cluster/manifests/dashboard/service.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/roles/readonly-binding.yaml
  cluster/manifests/roles/readonly-dashboard.yaml
  docs/user-guide/kubernetes-cheat-sheet.svg
Labels: minor

#8210 Update Tokeninfo to latest version
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#8214 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#8230 Revert to 1.30 AMI for eks
  cluster/config-defaults.yaml
Labels: bugfix

#8227 Make ssm session logging optional
  cluster/cluster.yaml
Labels: minor

#8232 Make eks okta identity provider optional
  cluster/cluster.yaml
  cluster/config-defaults.yaml
Labels: minor

#8233 e2e: Allow non ready nodes when starting e2e run
  test/e2e/README.md
  test/e2e/run_e2e.sh
Labels: minor

#8244 skipper: increase skipper_pod_deletion_cost_controller_poll_timeout
  cluster/config-defaults.yaml
Labels: minor

#8250 skipper: update main fleet version to v0.21.208
  cluster/manifests/skipper/deployment.yaml
Labels: major, dependencies

#8246 skipper-ingress: enable routesrv profiling
  cluster/manifests/skipper/deployment.yaml
Labels: minor
