Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-03, with the labels that each got.

#7108 karpenter: add .Values prefix
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#7118 Update StackSet controller version.
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: bugfix

#7120 skipper: update hostname-credentials-controller
  cluster/manifests/deletions.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
  cluster/manifests/skipper/secret-combiner.yaml
Labels: major

#7117 Make canary-only configuration for skipper-ingress possible
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7114 feature: ingress enable cert tag filter [1/2]
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/ingress-controller/deployment.yaml
Labels: architectural

#7126 fix: ingress controller aws permission issue found in dev
  cluster/cluster.yaml
Labels: bugfix

#7138 Karpenter setup modifications
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#6147 Update to Kubernetes v1.26
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/etcd/stack.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/manifests/aws-cloud-controller-manager/rbac.yaml
  cluster/manifests/deletions.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/audit.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/util.go
Labels: major

#7133 fix: skipper-ingress dataplane AWS role for OPA
  cluster/manifests/deletions.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/rbac.yaml
Labels: bugfix

#7144 routegroup: update CRD
  cluster/manifests/01-routegroup/routegroup-crd.yaml
Labels: documentation

#7123 Cleanup deletions
  cluster/manifests/deletions.yaml
Labels: do-not-merge, minor

#7146 fabric: update version to master-243
  cluster/config-defaults.yaml
Labels: dependencies

#7154 Fix string matching in e2e test
  test/e2e/apiserver.go
Labels: bugfix

#7151 Update unbound to v1.19.2
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: dependencies

#7140 Drop config items for configuration resources (enabled by default)
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  cluster/manifests/stackset-controller/rbac.yaml
Labels: minor

#7155 Rename config item for skipper health check
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7153 Update stackset-controller version to v1.4.52
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7134 Skipper: change routesrv svcaccount
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#7110 Create configuration to enable PHC in skipper main fleet pod
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#7160 Allow users to use coordination.k8s.io api for Leader election
  cluster/manifests/roles/poweruser-role.yaml
  cluster/manifests/roles/readonly-role.yaml
Labels: minor

#7135 skipper: svcaccount cleanup to least privileges
  cluster/manifests/deletions.yaml
  cluster/manifests/skipper/rbac.yaml
Labels: architectural

#7173 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#7179 Add support for inline ConfigMaps in StackSet CRD
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
Labels: minor

#7184 Only schedule coredns based on known taints
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#7182 Update to Kubernetes v1.27.12
  cluster/config-defaults.yaml
Labels: major

#7186 Only schedule coredns based on known taints
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#7187 feature: ingress enable cert tag filter [2/2]
  cluster/config-defaults.yaml
Labels: minor

#7174 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#6997 Update to Kubernetes v1.27
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/admission_controller.go
  test/e2e/apiserver.go
  test/e2e/audit.go
  test/e2e/aws_iam.go
  test/e2e/external_dns.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/gpu.go
  test/e2e/ingress.go
  test/e2e/kube_metrics_adapter_test.go
  test/e2e/node_test.go
  test/e2e/psp.go
  test/e2e/routegroup.go
Labels: major

#7201 Update to Prometheus v2.51.0
  cluster/manifests/prometheus/statefulset.yaml
Labels: minor

#7202 Update kube-metrics-adapter to Kubernetes v1.27
  cluster/manifests/kube-metrics-adapter/deployment.yaml
Labels: minor

#7200 Update to flannel v0.24.4
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#7206 Update kube-static-egress-controller to v1.27
  cluster/manifests/kube-static-egress-controller/deployment.yaml
Labels: dependencies

#7207 Update components to Kubernetes v1.27
  cluster/manifests/event-logger/statefulset.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/pdb-controller/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: dependencies

#7212 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#7214 routegroup crd: add hosts max length
  cluster/manifests/01-routegroup/routegroup-crd.yaml
Labels: minor

#7216 Update components to Kubernetes v1.27 (2)
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
  cluster/manifests/ingress-controller/deployment.yaml
  cluster/manifests/kube-node-ready-controller/daemonset.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor, dependencies

#7211 Update VPA to v1.0.0
  cluster/config-defaults.yaml
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/rbac.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
Labels: major

#7221 skipper: enable topology-spread by default
  cluster/config-defaults.yaml
Labels: minor

#7224 Update kube-aws-iam-controller to kubernetes 1.27
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
Labels: minor
