Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-01, with the labels that each got.

#6624 skipper: remove skipper_ingress_canary_args config item
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#6710 deploy: use test cluster for deploy-event
  delivery.yaml
Labels: minor

#6709 Disable legacy APIs by default
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: major

#6711 deploy: use teapot cluster for deploy-event
  delivery.yaml
Labels: minor

#6713 Don't create metrics with zero timestamp
  cluster/manifests/kubelet-summary-metrics/deployment.yaml
Labels: bugfix

#6712 Tag instance root volumes with application/component
  cluster/etcd/stack.yaml
  cluster/manifests/z-karpenter/configmap.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#6716 Only tag worker node volumes when updating to jammy
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#6718 skipper: disable catchall routes by default
  cluster/config-defaults.yaml
Labels: minor

#6719 Update skipper-ingress to deploy lock-free endpointregistry step2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#6721 update kube-ingress-aws-controller
  cluster/manifests/ingress-controller/deployment.yaml
Labels: dependencies

#6723 fix: skipper-ingress route lookup edge case with fabric and stackset 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#6566 remove ETCD_CLIENT_TLS_ENABLED from etcd env
  cluster/config-defaults.yaml
  cluster/etcd/stack.yaml
Labels: minor

#6728 Expose more metrics via kubelet-summary-metrics
  cluster/manifests/kubelet-summary-metrics/deployment.yaml
Labels: minor

#6730 update etcd AMI with logrotate fix
  cluster/config-defaults.yaml
Labels: bugfix

#6731 Add support for kubelet-cadvisor
  cluster/config-defaults.yaml
  cluster/manifests/node-monitor/daemonset.yaml
  cluster/manifests/node-monitor/service.yaml
  cluster/manifests/prometheus/configmap.yaml
Labels: minor

#6736 Adding ClusterRole and config-items for config-provider-service controller
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/roles/config-provider-rbac.yaml
Labels: minor

#6740 skipper: update main to v0.18.92-741
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#6737 use region variable
  cluster/manifests/kube-metrics-adapter/deployment.yaml
  cluster/manifests/skipper/configmap-open-policy-agent.yaml
Labels: minor

#6742 scrape: parca-agent option
  cluster/config-defaults.yaml
  cluster/manifests/prometheus/configmap.yaml
Labels: minor

#6744 skipper update: inserts OPA labels
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#6750 skipper update: inserts OPA labels - 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#6752 Update skipper version to introduce logBody() filter and normalize routing.Route host, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: major

#6754 prometheus: enable OAuth Grant flow for configured users
  cluster/config-defaults.yaml
  cluster/manifests/prometheus/ingress.yaml
Labels: minor

#6755 Update unbound DNS cache to 1.19.0
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: minor

#6760 Apply RouteGroup CRD earlier
  cluster/manifests/01-routegroup/routegroup-crd.yaml
Labels: bugfix

#6756 etcd: move scalyr key to files.yaml
  cluster/config-defaults.yaml
  cluster/etcd/files.yaml
  cluster/etcd/stack.yaml
Labels: minor

#6764 Update ensure-apiserver for optional ipv6 support
  cluster/manifests/coredns-local/daemonset-coredns.yaml
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#6763 Update admission-controller to update deps
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6762 allow dax:DescribeClusters for zmon
  cluster/cluster.yaml
Labels: minor

#6753 Update skipper version to introduce logBody() filter and normalize routing.Route host, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: major

#6772 Updated skipper version to use endpointregistry in the hotpath, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#6776 remove unused version field from manifests
  cluster/manifests/dashboard/deployment.yaml
  cluster/manifests/dashboard/scraper.yaml
  cluster/manifests/efs-provisioner/depl-efs-provisioner.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/manifests/kube2iam/daemonset.yaml
  cluster/manifests/kubenurse/prometheus.yaml
  cluster/manifests/pdb-controller/deployment.yaml
  docs/user-guide/using-volumes.rst
  test/e2e/loadtest/client/prom-statefulset.yaml
Labels: minor

#6781 update ExternalDNS to v0.13.6
  cluster/manifests/external-dns/deployment.yaml
Labels: minor

#6787 update etcd.py to v3 API
  cluster/config-defaults.yaml
Labels: major, updates/etcd

#6773 Updated skipper version to use endpointregistry in the hotpath, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#6792 Use AILM provided Deployment Key in end 2 end tests.
  cluster/cluster.yaml
Labels: minor

#6795 templatise etcd AMI
  cluster/config-defaults.yaml
Labels: minor

#6796 [ALPHA] templatise etcd AMI
  cluster/config-defaults.yaml
Labels: minor

#6794 Update kube-janitor to latest version
  cluster/manifests/kube-janitor/deployment.yaml
Labels: minor

#6798 Update to flannel v0.24.1
  cluster/manifests/flannel/daemonset.yaml
Labels: minor

#6780 update stackset-controller's e2e test and enable configmap support in e2e tests
  cluster/config-defaults.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#6799 Update to Prometheus v2.49.1
  cluster/manifests/prometheus/statefulset.yaml
Labels: minor

#6803 Synchronize annotation feature for StackSet.
  cluster/config-defaults.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/cluster_config.sh
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: do-not-merge, minor

#6805 skipper-ingress: hpa max 300 replicas for prod
  cluster/config-defaults.yaml
Labels: minor

#6732 Implement PSP in admission-controller
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/psp/pod_security_policy.yaml
  cluster/node-pools/master-default/userdata.yaml
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/psp.go
  test/e2e/util.go
Labels: major

#6814 Revert faulty etcd AMI on dev.
  cluster/config-defaults.yaml
Labels: bugfix

#6808 all: add .Cluster prefix to .ConfigItems
  cluster/manifests/01-admission-control/skipper-webhook.yaml
  cluster/manifests/01-admission-control/teapot.yaml
  cluster/manifests/01-vertical-pod-autoscaler/02-secret.yaml
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
  cluster/manifests/02-kube-aws-iam-controller/vpa.yaml
  cluster/manifests/03-ebs-csi/controller.yaml
  cluster/manifests/03-ebs-csi/vpa.yaml
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/coredns-local/configmap-local.yaml
  cluster/manifests/default-limits/limits.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/deployment-service/status-service-secret.yaml
  cluster/manifests/efs-provisioner/cm-efs-provisioner.yaml
  cluster/manifests/efs-provisioner/depl-efs-provisioner.yaml
  cluster/manifests/efs-provisioner/rbac.yaml
  cluster/manifests/efs-provisioner/sc-aws-efs.yaml
  cluster/manifests/emergency-access-service/secret.yaml
  cluster/manifests/etcd-backup/cronjob.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/external-dns/vpa.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
  cluster/manifests/kube-janitor/rules-config.yaml
  cluster/manifests/kube-state-metrics/deployment.yaml
  cluster/manifests/kube-state-metrics/vpa.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/vpa.yaml
  cluster/manifests/metrics-server/deployment.yaml
  cluster/manifests/metrics-server/metrics-server-vpa.yaml
  cluster/manifests/node-monitor/daemonset.yaml
  cluster/manifests/prometheus/configmap.yaml
  cluster/manifests/prometheus/credentialset.yaml
  cluster/manifests/prometheus/prometheus-vpa.yaml
  cluster/manifests/prometheus/rbac.yaml
  cluster/manifests/prometheus/statefulset.yaml
  cluster/manifests/skipper/configmap-open-policy-agent.yaml
  cluster/manifests/skipper/configmap-sandbox-tokeninfo-bridge.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
  cluster/manifests/skipper/hpa-redis.yaml
  cluster/manifests/skipper/hpa-routesrv.yaml
  cluster/manifests/skipper/rbac.yaml
  cluster/manifests/skipper/routesrv-service.yaml
  cluster/manifests/skipper/secret-combiner.yaml
  cluster/manifests/skipper/skipper-redis.yaml
  cluster/manifests/spot-node-rescheduler/cronjob.yaml
  cluster/manifests/spot-node-rescheduler/rbac.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  cluster/manifests/stackset-controller/vpa.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6818 coredns-local: fix variable scope
  cluster/manifests/coredns-local/configmap-local.yaml
Labels: minor

#6815 fabric-gateway: update controller version to master-234
  cluster/config-defaults.yaml
Labels: major

#6820 Allow deployment service role to decrypt any secret.
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
Labels: minor

#6769 skipper: cleanup skipper_ingress_opentracing_excluded_proxy_tags
  cluster/config-defaults.yaml
Labels: minor

#6812 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: major

#6747 Update Audittrail to allow Nakadi functionality
  cluster/config-defaults.yaml
  cluster/manifests/audittrail-adapter/credentials.yaml
  cluster/manifests/audittrail-adapter/daemonset.yaml
Labels: major

#6829 bump deployment-service version
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#6831 Update skipper version to decouple fadein from loadbalancer and tighten validation, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#6836 Revert "Update Audittrail to allow Nakadi functionality"
  cluster/config-defaults.yaml
  cluster/manifests/audittrail-adapter/credentials.yaml
  cluster/manifests/audittrail-adapter/daemonset.yaml
Labels: major

#6837 Revert "Update Audittrail to allow Nakadi functionality"
  cluster/config-defaults.yaml
  cluster/manifests/audittrail-adapter/credentials.yaml
  cluster/manifests/audittrail-adapter/daemonset.yaml
Labels: major

#6840 Allow safe sysctl in new PSP implementation
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6847 Add ConfigMap to hyped-articles-lifecycle-management controller role
  cluster/manifests/roles/hyped-articles-lifecycle-rbac.yaml
Labels: bugfix

#6832 Update skipper version to decouple fadein from loadbalancer and tighten validation, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#6857 Add option to inject NODE_OPTIONS envvar
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#6859 kube-cluster-autoscaler: add .Cluster prefix
  cluster/manifests/kube-cluster-autoscaler/buffer-pods-deployment.yaml
Labels: minor

#6858 Update to nvidia-device-plugin v0.14.4
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#6864 Update CA to support more instance-types
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: minor

#6863 Remove deployment key and config items.
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
Labels: minor

#6835 skipper-admission-webhook: update skipper images/apps in master nodes
  cluster/node-pools/master-default/userdata.yaml
Labels: major

#6838 Update stackset-controller to the latest version
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#6872 Update admission-controller with granular node options fix
  cluster/node-pools/master-default/userdata.yaml
Labels: minor
