Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-06, with the labels that each got.

#7618 Don't bind collaborator to PowerUser access
  cluster/manifests/roles/poweruser-binding.yaml
Labels: bugfix

#7626 fabric-gateway: update to master-254
  cluster/config-defaults.yaml
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: dependencies

#7630 fabric-gateway: update CRD
  cluster/manifests/fabric-gateway/deployment.yaml
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: major

#7631 ingress-controller: update to v0.15.19
  cluster/manifests/ingress-controller/deployment.yaml
Labels: dependencies

#7609 Update to kube2iam 0.11.2 + static base image
  cluster/manifests/kube2iam/daemonset.yaml
Labels: major

#7621 Update kube-metrics-adapter to static base image
  cluster/manifests/kube-metrics-adapter/deployment.yaml
Labels: major

#7622 Update stackset-controller to use a static base image
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: major

#7620 admission-controller: Handle config defined capabilities [2/2]
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7636 Update kubenurse to v1.13.1
  cluster/manifests/kubenurse/daemonset.yaml
Labels: major

#7634 add config-item to toggle nvidia-dcgm-exporter sidecar
  cluster/config-defaults.yaml
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#7597 Update to Karpenter v0.37.0
  cluster/config-defaults.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: major

#7613 skipper: use amazonlinux slim again but with `curl` (step 2/2)
  cluster/manifests/skipper/deployment.yaml
Labels: architectural

#7647 Update kube-dns images to latest version 1.23.1
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: major

#7646 Update kube-aws-iam-controller to static base image
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
Labels: major

#7648 Update skipper version, step 1/2
  cluster/manifests/skipper/deployment.yaml
Labels: major, minor, dependencies

#7654 skipper: remove deprecated flags
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7663 Revert "Update kube-dns images to latest version 1.23.1"
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#7664 [HOTFIX v1.30] Revert "Update kube-dns images to latest version 1.23.1"
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#7668 Update kube-aws-iam-controller to aws-sdk-go-v2
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
Labels: minor

#7666 Remove legacy Runtime policy toggle
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
Labels: minor

#7661 [deployment-service] update cdpdeploymenttaskresource phases in CRD
  cluster/manifests/deployment-service/00-crd.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7649 Update skipper version, step 2/2
  cluster/manifests/skipper/deployment.yaml
Labels: major, minor, dependencies

#7670 Update admission-controller drop runtime policy
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7676 skipper: add config to enable prometheus start label
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7687 [deployment-service] update version and CRD
  cluster/manifests/deployment-service/00-crd.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7688 Update to Kubernetes v1.30.2
  cluster/config-defaults.yaml
Labels: major

#7692 Update e2e to latest Kubernetes version
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: minor

#7695 fix ebs-csi-node RBAC for ebs-csi-driver
  cluster/manifests/03-ebs-csi/clusterrole-csi-node.yaml
Labels: do-not-merge, bugfix

#7696 Align deployment-service config key with reality
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#7705 update kubernetes-lifecycle-metrics version
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
Labels: minor

#7628 Make use of kube-scheduler's config file
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7706 Update vulnerable Go deps
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies

#7709 update kubernetes-lifecycle-metrics
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
  cluster/manifests/kubernetes-lifecycle-metrics/rbac.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: bugfix

#7714 flip the order of nvidia driver's nodeAffinities to mitigate a karpenter bug
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor

#7717 label nodes by profile, used to enrich metrics
  cluster/node-pools/worker-splitaz/userdata.yaml
Labels: minor

#7720 skipper: update canary to version v0.21.124
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#7722 Update deployment-service to master-202
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7728 Update deployment-service to master-203
  cluster/manifests/deployment-service/01-config.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: minor

#7729 Updates CLC to use aws-sdk-go-v2
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
Labels: minor

#7725 Rotate nodes with old daemonset pods before e2e
  test/e2e/.gitignore
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/daemonset-updated/main.go
  test/e2e/run_e2e.sh
Labels: minor

#7735 Revert "Patch kube-scheduler to fix crash"
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#7734 [Kubernetes v1.30] beta to stable
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/admission_controller.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: updates/worker-nodes, updates/master-nodes, major

#7361 Update to Kubernetes v1.30
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/admission_controller.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: major

#7739 fabric-gateway: update to master-256
  cluster/manifests/fabric-gateway/deployment.yaml
Labels: minor

#7738 skipper: set skipper_prometheus_start_label_enabled by default
  cluster/config-defaults.yaml
Labels: minor

#7746 fix: routesrv metrics port was changed to 9911 a while ago
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#7745 ingress-controller: configure keyValue log parser
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor

#7724 skipper: update main fleet to version v0.21.124
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#7749 Kubernetes v1.30.2 components [1/X]
  cluster/manifests/02-kube-aws-iam-controller/deployment.yaml
  cluster/manifests/kube-metrics-adapter/deployment.yaml
  cluster/manifests/pdb-controller/deployment.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#7751 egress: Update to Kubernetes v1.30.2 + aws-sdk-go-v2
  cluster/manifests/kube-static-egress-controller/deployment.yaml
Labels: minor

#7752 Kubernetes v1.30.2 components [2/X]
  cluster/manifests/03-ebs-csi/controller.yaml
  cluster/manifests/03-ebs-csi/node.yaml
  cluster/manifests/cluster-lifecycle-controller/deployment.yaml
  cluster/manifests/ingress-controller/deployment.yaml
Labels: dependencies

#7757 skipper: update canary version to v0.21.133
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#7762 admission-controller: Native sleep preStop hook
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#7758 Disable cadvisor by default
  cluster/config-defaults.yaml
Labels: minor

#7764 Update nvidia device plugin to v0.15.1
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: minor
