Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-10, with the labels that each got.

#8242 eks: aws-node update to latest cni plugin version
  cluster/manifests/01-aws-node/daemonset.yaml
Labels: minor

#8254 fix: skipper topologySpreadConstraints.labelSelector
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#8243 Provide AWS credentials to aws-node via eks-pod-identity
  cluster/cluster.yaml
  cluster/manifests/01-aws-node/sa.yaml
Labels: do-not-merge, minor

#8256 fix: topology spread timeout
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor

#8264 skipper-ingress: update canary to v0.21.211
  cluster/manifests/skipper/deployment.yaml
Labels: dependencies

#8260 Allow powerusers to also delete leases
  cluster/manifests/roles/poweruser-role.yaml
Labels: minor

#8263 Optionally Audit controller-manager node changes
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#8272 skipper: add server connection keepalive limits
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: major

#8249 Experimental support for ipv6
  cluster/manifests/01-coredns-local/configmap-local.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/manifests/skipper/service-internal.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#8273 skipper-ingress: update main fleet to v0.21.211
  cluster/manifests/skipper/deployment.yaml
Labels: dependencies

#8274 Update stackset-controller to Kube v1.31
  cluster/manifests/stackset-controller/01-stack-crd.yaml
  cluster/manifests/stackset-controller/01-stackset-crd.yaml
  cluster/manifests/stackset-controller/deployment.yaml
  delivery.yaml
  test/e2e/go.mod
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: minor

#8290 ingress-controller: enable image-updater-bot
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor

#8291 deployment-service,kube-janitor,kube-node-ready: enable image-updater-bot
  cluster/manifests/deployment-service/status-service-deployment.yaml
  cluster/manifests/kube-janitor/deployment.yaml
  cluster/manifests/kube-node-ready/daemonset.yaml
Labels: minor

#8300 eks: Support dynamic IPv4 service CIDR
  cluster/manifests/01-coredns-local/configmap-local.yaml
  cluster/manifests/skipper/service-internal.yaml
Labels: minor

#8308 fix: use resync as default in pod deletion cost controller
  cluster/config-defaults.yaml
Labels: bugfix

#8312 skipper-canary-controller: update cronjob lightstep enviroment variables
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: minor

#8304 Fix ingress.cluster.local feature for eks
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#8329 Update skipper-ingress main fleet to v0.21.216-1038
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#8331 skipper-canary-controller: remove `LIGHTSTEP_DEBUG`
  cluster/manifests/skipper-canary-controller/canary-cronjob.yaml
Labels: minor

#8328 prometheus: ipv6 pod support
  cluster/manifests/prometheus/configmap.yaml
Labels: minor

#8334 drop deprecated annotation from skipper-ingress Service
  cluster/manifests/skipper/service-internal.yaml
Labels: minor

#8343 fabric: enable versioning by default
  cluster/config-defaults.yaml
Labels: minor

#8358 Introduce S3 csi driver (disabled by default)
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/s3-csi-driver/csidriver.yaml
  cluster/manifests/s3-csi-driver/daemonset.yaml
  cluster/manifests/s3-csi-driver/rbac.yaml
Labels: minor

#8281 bugfix: add dedicated label to requirements
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix

#8326 EKS: Make e2e work
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/zalando-iam-aws-proxy/routegroup.yaml
  delivery.yaml
  test/e2e/cluster_config.sh
  test/e2e/run_e2e.sh
  test/e2e/toggle-scaledown.py
Labels: minor

#8379 [manual] dev to eks
  cluster/manifests/skipper/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix, minor

#8372 static-egress upload CF template to s3
  cluster/cluster.yaml
  cluster/manifests/kube-static-egress-controller/deployment.yaml
Labels: minor

#8395 Fix podCIDR handling in kube-controller-manager
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#8364 Allow higher memory limit for flannel and kube-proxy
  cluster/config-defaults.yaml
  cluster/manifests/flannel/daemonset.yaml
  cluster/manifests/kube-proxy/daemonset.yaml
Labels: major

#8406 Exclude *5d.large instances in karpenter
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#8407 Make it possible to use IRSA for ZMON IAM role [1/2]
  cluster/cluster.yaml
Labels: minor

#8419 skipper: disable setRequestHeaderFromSecret filter
  cluster/config-defaults.yaml
Labels: major

#8389 Enable Zalando AWS IAM e2e test
  cluster/config-defaults.yaml
  test/e2e/aws_iam.go
  test/e2e/run_e2e.sh
Labels: minor

#7617 flex karpenter node-pool configurations
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#8426 Make kube-node-ready optional
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/kube-node-ready/01-rbac.yaml
  cluster/manifests/kube-node-ready/daemonset.yaml
  cluster/manifests/kube-node-ready/service.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#8432 Set AWS_DEFAULT_REGION for kube2iam
  cluster/manifests/kube2iam/daemonset.yaml
Labels: bugfix

#8437 skipper: update main to v0.21.220
  cluster/manifests/skipper/deployment.yaml
Labels: dependencies

#8440 Allow to separate subnets for LBs and nodes
  cluster/cluster.yaml
Labels: minor

#8461 allow zmon to list kinesisanalyticsv2 / kinesisanalytics applications
  cluster/cluster.yaml
Labels: minor

#8468 Fail nvidia-plugin on initialization error
  cluster/manifests/nvidia/nvidia-gpu-device-plugin.yaml
Labels: bugfix

#8474 add ZalandoCloud-AllowPowerUserCustom policy
  cluster/cluster.yaml
Labels: minor

#8482 add role-sync-controller cronjob
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/role-sync-controller/cronjob.yaml
  cluster/manifests/role-sync-controller/rbac.yaml
  cluster/manifests/role-sync-controller/service-account.yaml
Labels: architectural

#8481 Use local endpoint for deployment-controller to status-service
  cluster/manifests/deployment-service/01-config.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
  cluster/manifests/deployment-service/status-service-ingress.yaml
Labels: minor

#8485 Improvements to role-sync-controller cronjob
  cluster/manifests/role-sync-controller/cronjob.yaml
Labels: bugfix, minor

#8488 fix RBAC for role-sync-controller
  cluster/manifests/deletions.yaml
  cluster/manifests/role-sync-controller/rbac.yaml
Labels: bugfix
