Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2024-11, with the labels that each got.

#8504 Register `/rolebinding` admitter in order to reject certain rolebindings
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/teapot.yaml
Labels: minor

#8506 Remove former colleagues from zappr.yaml
  .zappr.yaml
Labels: documentation

#8503 Use Cluster.Name in all cases
  cluster/manifests/01-aws-node/daemonset.yaml
  cluster/manifests/zalando-iam-aws-proxy/deployment.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
Labels: minor

#8507 Optional internal control plane LB
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
Labels: minor

#8519 Register generic admitter for write protection behind a feature flag
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/manifests/01-admission-control/teapot.yaml
  cluster/manifests/prometheus/rbac.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#8514 update deployment-service components
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-deployment.yaml
Labels: bugfix

#8524 make kube-janitor opt-in for production clusters
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/kube-janitor/deployment.yaml
  cluster/manifests/kube-janitor/rbac.yaml
  cluster/manifests/kube-janitor/rules-config.yaml
  cluster/manifests/kube-janitor/vpa.yaml
Labels: minor

#8528 update role-sync-controller and use CLI parameters for subjects
  cluster/manifests/role-sync-controller/cronjob.yaml
Labels: minor

#8531 Drop unused eks config-item
  cluster/config-defaults.yaml
Labels: minor

#8532 [e2e] Refactor RBAC tests to use client-go instead of raw HTTP
  cluster/config-defaults.yaml
  test/e2e/authorization.go
  test/e2e/authorization_utils.go
Labels: major, e2e

#8529 [EKS] switch to generic deny-all admitter, match conditions and fail policy
  cluster/config-defaults.yaml
  cluster/manifests/02-admission-control/deployment.yaml
  cluster/manifests/02-admission-control/teapot.yaml
Labels: minor

#8537 [RBAC] drop secret read permission from poweruser ClusterRole
  cluster/manifests/roles/collaborator-roles.yaml
  cluster/manifests/roles/poweruser-role.yaml
Labels: minor

#8536 [e2e] Improvements on the RBAC e2es
  test/e2e/authorization.go
Labels: minor, e2e

#8539 [e2e] Skip authz test for access handled by admission-controller
  test/e2e/authorization.go
Labels: minor, e2e

#8541 Update custom metrics image to work with ipv6
  test/e2e/kube_metrics_adapter_test.go
Labels: bugfix, e2e

#8538 Update aws-node daemonset to v1.19
  cluster/manifests/01-aws-node/config.yaml
  cluster/manifests/01-aws-node/daemonset.yaml
Labels: minor

#8542 Exclude eks-pod-identity-agent from admission-controller to avoid 🐔🥚
  cluster/manifests/02-admission-control/teapot.yaml
Labels: bugfix

#8547 Scrape metrics from EKS control plane
  cluster/manifests/prometheus/configmap.yaml
Labels: minor
