Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-01, with the labels that each got.

#8684 skipper-internal: update main fleet to version v0.21.240-1063
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#8691 [e2e] upgrade instance types
  test/e2e/cluster_config.sh
Labels: minor, e2e

#8690 use upgraded instance types in default-for-karpenter
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#8712 Update dependencies
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/stackset/go.mod
  test/e2e/stackset/go.sum
Labels: dependencies

#8692 add aws-efa-device-plugin manifests
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/manifests/aws-efa-device-plugin/daemonset.yaml
  cluster/manifests/aws-efa-device-plugin/rbac.yaml
  cluster/manifests/deletions.yaml
Labels: major

#8730 Use default kube-controller-manager image
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#8733 Allow configuring associatePublicIp on instance launch
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#8738 Set prefix delegation false by default
  cluster/config-defaults.yaml
Labels: minor

#8685 [e2e] use p4 instead of old p3 instances
  test/e2e/cluster_config.sh
Labels: do-not-merge, minor, e2e

#8741 Pass Account Name to to deployment-service
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#8742 Configure associate Public IP at node Pool level
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#8758 Add optional support for internel node subnets
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#8765 fabric: update crd
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#8774 skipper: update main to v0.21.247
  cluster/manifests/skipper/deployment.yaml
Labels: major, minor, dependencies

#8780 Make internal subnet control associate-public-ip
  cluster/config-defaults.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
Labels: minor

#8786 Fix forwarded headers exclude cirds for IPv6
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#8793 master-node-autoscaler: add config-item to disable instance generation downgrade
  cluster/config-defaults.yaml
Labels: minor

#8797 [manual] dev to eks
  cluster/manifests/02-admission-control/config.yaml
  cluster/manifests/audittrail-adapter/daemonset.yaml
Labels: minor

#8802 .zappr.yaml: add vlktna
  .zappr.yaml
Labels: documentation

#8801 fabric: update crd
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#8805 e2e: remove EoL g3 instances from e2e pool
  test/e2e/cluster_config.sh
Labels: minor

#8825 Apply best practices for role-sync cronjob
  cluster/manifests/role-sync-controller/cronjob.yaml
Labels: minor

#8812 skipper: update main to v0.21.257
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: do-not-merge, major

#8841 Correctly exclude wiz from node readiness check
  cluster/manifests/wiz/sensor-daemonset.yaml
Labels: bugfix

#8843 Fix typo in wiz-sensor service account name
  cluster/manifests/01-admission-control/config.yaml
Labels: bugfix

#8575 Add ingress test for opaAuthorizeRequest filter
  cluster/manifests/skipper/01-rbac.yaml
  delivery.yaml
  test/e2e/aaas.go
  test/e2e/apply/secret.yaml
  test/e2e/cluster_config.sh
  test/e2e/run_e2e.sh
Labels: minor, e2e

#8846 Give kube-metrics-adapter permissions to scale deployments/statefulsets
  cluster/manifests/kube-metrics-adapter/01-rbac.yaml
Labels: bugfix
