Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-09, with the labels that each got.

#9801 Allow downscaling statefulsets
  cluster/config-defaults.yaml
  cluster/manifests/kube-downscaler/deployment.yaml
Labels: minor

#9651 FabricGateway: Add ValidatingAdmissionPolicy
  cluster/manifests/fabric-gateway/02-validation.yaml
Labels: major

#9824 fg: make `ValidatingAdmissionWebhook` customizable
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/fabric-gateway/02-validation.yaml
Labels: minor

#9810 Re-enable EKS Control Plane logging in e2es
  test/e2e/cluster_config.sh
Labels: minor

#9841 eks-pod-identity-agent: Update to latest version
  cluster/cluster.yaml
Labels: minor

#9840 [EKS] Manage kube-proxy as an addon
  cluster/cluster.yaml
  cluster/manifests/02-admission-control/teapot.yaml
Labels: minor

#9847 profiling: add label data cluster region zone
  cluster/manifests/polarsignals/daemonset.yaml
Labels: minor

#9523 Update to Kubernetes v1.33
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/02-admission-control/teapot.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/apiserver.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: do-not-merge, major

#9911 skipper-ingress: fix main image formatting
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9919 Exclude kube-proxy in admission config
  cluster/manifests/02-admission-control/teapot.yaml
Labels: bugfix

#9915 skipper: rename main image variable
  cluster/manifests/skipper/deployment.yaml
Labels: documentation

#9922 Do not allow Karpenter to disrupt nodes due to Drift
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#9921 skipper-internal: Update main fleet to version v0.22.115-1222
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major, minor, documentation, dependencies

#9770 update flannel DaemonSet strategy to RollingUpdate
  cluster/manifests/flannel/daemonset.yaml
Labels: do-not-merge, bugfix

#9927 Update e2e test to latest Kubernetes v1.33 version
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: dependencies

#9929 Update default-for-karpenter 7th / 8th gen instances
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: major
