Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-04, with the labels that each got.

#9164 Excempt wiz namespace from being downscaled in test clusters
  cluster/manifests/kube-downscaler/deployment.yaml
Labels: minor

#9156 Switch deployment targets from `stups-test` to `stups-euc1-test`
  delivery.yaml
  test/e2e/apply/pcs.yaml
  test/e2e/apply/pdb.yaml
Labels: minor

#9168 fix requirement for encryption in-transit
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix

#9176 karpenter: Only allow nitro instances
  cluster/config-defaults.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#9182 lifecycle-metrics: Reduce pod rescheduling
  cluster/manifests/kubernetes-lifecycle-metrics/deployment.yaml
Labels: bugfix

#9188 Add RBAC for kubernetes-unit-costs
  cluster/manifests/roles/kubernetes-unit-costs.yaml
Labels: minor

#9181 kube2iam: Fix for EKS ipv6
  cluster/config-defaults.yaml
  cluster/manifests/02-admission-control/config.yaml
  cluster/manifests/kube2iam/daemonset.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  test/e2e/run_e2e.sh
Labels: major

#9170 Configure response header timeouts for styra calls
  cluster/config-defaults.yaml
  cluster/manifests/skipper/configmap-open-policy-agent.yaml
Labels: minor

#9191 Avoid userdata change
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
Labels: bugfix

#9190 Loadtest prometheus ipv6 pod support
  test/e2e/loadtest/client/prom-configmap.yaml
Labels: bugfix

#9052 Test the upgrade path of EKS clusters in e2e tests
  test/e2e/apply/config.yaml
  test/e2e/run_e2e.sh
Labels: minor

#9157 skipper-internal: Update main version to v0.22.7-1117
  cluster/manifests/skipper/deployment.yaml
Labels: dependencies

#9198 Only attach skipper nodes to NLB in e2e
  cluster/config-defaults.yaml
Labels: minor

#9203 Add custom PDB for skipper-ingress covering main and canary deployment
  cluster/config-defaults.yaml
  cluster/manifests/skipper/pdb.yaml
Labels: bugfix

#9194 Set unbound as default dns_cache
  cluster/config-defaults.yaml
Labels: major

#9119 Mainly use karpenter pools for e2e
  cluster/manifests/e2e-resources/pool-reserve.yaml
  test/e2e/cluster_config.sh
  test/e2e/infra.go
  test/e2e/util.go
Labels: minor

#9130 e2e: Increase instance-type choices
  test/e2e/cluster_config.sh
Labels: minor

#9215 [HOTFIX] dev to alpha e2e hotfix
  cluster/manifests/e2e-resources/pool-reserve.yaml
  test/e2e/cluster_config.sh
  test/e2e/infra.go
  test/e2e/util.go
Labels: minor

#9217 [HOTFIX] beta to stable e2e fix
  cluster/manifests/e2e-resources/pool-reserve.yaml
  test/e2e/cluster_config.sh
  test/e2e/infra.go
  test/e2e/util.go
Labels: minor

#9218 skipper: whitelist IPv6 CIDR
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9222 Revert skipper-internal: Update main version to v0.22.7-1117
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix

#9226 Allow Manual role Admin access in e2e clusters
  cluster/cluster.yaml
Labels: minor

#9221 Add taint to arm64 pool
  cluster/manifests/e2e-resources/pool-reserve.yaml
  test/e2e/cluster_config.sh
Labels: bugfix

#9214 Update the CRD for (cluster)scalingschedules
  cluster/manifests/kube-metrics-adapter/cluster_scaling_schedules_crd.yaml
  cluster/manifests/kube-metrics-adapter/scaling_schedules_crd.yaml
Labels: minor

#9234 exclude a1 instance family from Karpenter pools
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix

#9147 remove the unused karpenter_pools_enabled config-item
  cluster/config-defaults.yaml
Labels: minor

#9213 Disable emergency-access-service by default
  cluster/config-defaults.yaml
Labels: major

#9229 Redeploy skipper-internal: Update main version to v0.22.7-1117
  cluster/manifests/skipper/deployment.yaml
Labels: major

#9276 e2e: only consolidate empty nodes
  test/e2e/cluster_config.sh
Labels: bugfix

#9280 Update to Kubernetes v1.32.4
  cluster/config-defaults.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: minor

#9284 allow excluding t type instances from Karpenter node-pools
  cluster/config-defaults.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#9272 Only update flannel OnDelete
  cluster/manifests/flannel/daemonset.yaml
  test/e2e/daemonset-updated/main.go
Labels: bugfix

#9206 skipper-ingress: explicit healthcheck routes on the pod level
  cluster/manifests/skipper/deployment.yaml
Labels: major

#9307 Remove emergency-access-service
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/emergency-access-service/01-rbac.yaml
  cluster/manifests/emergency-access-service/credentials.yaml
  cluster/manifests/emergency-access-service/deployment.yaml
  cluster/manifests/emergency-access-service/ingress.yaml
  cluster/manifests/emergency-access-service/secret.yaml
  cluster/manifests/emergency-access-service/service.yaml
Labels: minor

#9279 Add the `aws-load-balancer-controller` to support ServiceType LoadBalancer on EKS
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/02-admission-control/config.yaml
  cluster/manifests/02-admission-control/deployment.yaml
  cluster/manifests/aws-load-balancer-controller/deployment.yaml
  cluster/manifests/aws-load-balancer-controller/ingressclassparams.yaml
  cluster/manifests/aws-load-balancer-controller/rbac.yaml
  cluster/manifests/aws-load-balancer-controller/serviceaccount.yaml
  cluster/manifests/aws-load-balancer-controller/targetgroupbindings.yaml
  cluster/manifests/aws-load-balancer-controller/vpa.yaml
  test/e2e/run_e2e.sh
Labels: minor

#9321 Use newer and recommended TLS 1.3 security policy for NLBs
  cluster/manifests/aws-load-balancer-controller/deployment.yaml
Labels: minor
