Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-10, with the labels that each got.

#9964 skipper/hostname-credentials-controller: configure ttlSecondsAfterFinished
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#9972 skipper/hostname-credentials-controller: fix ttlSecondsAfterFinished
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#9973 remove hyped articles rbac manifest
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/roles/hyped-articles-lifecycle-rbac.yaml
Labels: minor

#9974 crd: routegroup with <forward>
  cluster/manifests/02-routegroup/routegroup-crd.yaml
Labels: minor

#9817 Add eks fis v2 support
  cluster/manifests/02-admission-control/config.yaml
  cluster/manifests/eks-fis/01-rbac.yaml
  cluster/manifests/role-sync-controller/cronjob.yaml
  cluster/manifests/role-sync-controller/rbac.yaml
Labels: minor

#9992 Drop eks_fis_namespaces config-item
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
Labels: minor

#9994 Default e2e pools to amd64
  test/e2e/cluster_config.sh
Labels: bugfix

#9969 Update to platform-iam-tokeninfo built from GHEC
  cluster/manifests/zalando-iam-aws-proxy/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#9998 Revert "remove hyped articles rbac manifest"
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/roles/hyped-articles-lifecycle-rbac.yaml
Labels: minor

#10000 [CHERRY-PICK-ALPHA] Revert "remove hyped articles rbac manifest"
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/roles/hyped-articles-lifecycle-rbac.yaml
Labels: minor

#9990 fix: update skipper validation webhook version to enable forward backend
  cluster/manifests/02-skipper-validation-webhook/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: bugfix

#9924 Update to Karpenter v1.7.1
  cluster/manifests/z-karpenter/05-clusterrole-core.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: major
