Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-08, with the labels that each got.

#9741 exclude g6f instance family from Karpenter nodepools
  cluster/config-defaults.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix, minor

#9758 skipper: update main to v0.22.76
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major, dependencies

#9761 Update to Karpenter v1.6.0
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#9768 Add string docs for RBAC read-only testing
  test/e2e/authorization.go
Labels: minor

#9777 Add Log Group with expiring retention period for EKS Control Plane logging
  cluster/cluster.yaml
  cluster/config-defaults.yaml
Labels: minor

#9782 update 1.33 to kubernetes 1.33.4
  cluster/config-defaults.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
Labels: minor

#9784 Adding playground poweruser policy to deployment services
  cluster/cluster.yaml
Labels: minor

#9791 Polarsignals ds fixes
  cluster/manifests/polarsignals/daemonset.yaml
Labels: bugfix

#9803 skipper-ingress-redis: use image variable
  cluster/manifests/skipper/skipper-redis.yaml
Labels: minor

#9808 Fix polarsignals annotation
  cluster/manifests/polarsignals/daemonset.yaml
Labels: bugfix
