Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-07, with the labels that each got.

#9633 Make deployment-service roles configurable
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/01-config.yaml
  cluster/manifests/deployment-service/controller-rbac.yaml
  cluster/manifests/deployment-service/status-service-rbac.yaml
Labels: minor

#9620 feat: Add sandbox controller configuration, disabled by default.
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/sandbox-controller/10-sandbox_crd.yaml
  cluster/manifests/sandbox-controller/20-rbac.yaml
  cluster/manifests/sandbox-controller/30-deployment.yaml
Labels: minor

#9632 Make coredns tolerate the karpenter dedicated taint
  cluster/manifests/01-coredns-local/daemonset-coredns.yaml
Labels: bugfix

#9629 Use cluster's member function instead of template functions
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/02-admission-control/config.yaml
  cluster/manifests/aws-load-balancer-controller/serviceaccount.yaml
  cluster/manifests/aws-node-decommissioner/01-rbac.yaml
  cluster/manifests/deployment-service/01-config.yaml
  cluster/manifests/deployment-service/controller-rbac.yaml
  cluster/manifests/deployment-service/controller-statefulset.yaml
  cluster/manifests/deployment-service/status-service-rbac.yaml
  cluster/manifests/external-dns/01-rbac.yaml
  cluster/manifests/ingress-controller/01-rbac.yaml
  cluster/manifests/kube-cluster-autoscaler/01-rbac.yaml
  cluster/manifests/kube-metrics-adapter/01-rbac.yaml
  cluster/manifests/kube-static-egress-controller/deployment.yaml
  cluster/manifests/skipper/01-rbac.yaml
  cluster/manifests/skipper/configmap-open-policy-agent.yaml
  cluster/manifests/z-karpenter/01-serviceaccount.yaml
  cluster/manifests/zalando-iam-aws-proxy/deployment.yaml
  cluster/manifests/zalando-iam-aws-proxy/rbac.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#9647 pod-metric: adds availability zone label to pod metrics
  cluster/config-defaults.yaml
Labels: minor

#9662 Make WIZ Connector default config items conditional to cluster provider
  cluster/config-defaults.yaml
Labels: minor

#9676 Revert "Make WIZ Connector default config items conditional to cluster provider"
  cluster/config-defaults.yaml
Labels: bugfix

#9705 skipper: update main to v0.22.62
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major, dependencies

#9706 ingress-controller: comment template actions
  cluster/manifests/ingress-controller/deployment.yaml
Labels: minor

#9725 add EFS SG definition and rule for EKS cluster
  cluster/cluster.yaml
Labels: minor

#9728 [STABLE] Revert "beta to stable"
  cluster/manifests/02-skipper-validation-webhook/deployment.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
  test/e2e/go.mod
Labels: bugfix

#9730 updating cluster autoscaler version
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#9731 [HOTFIX] [STABLE] Update cluster autoscaler version
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#9737 [ALPHA] [HOTFIX] Update Cluster Autoscaler version
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#9739 [BETA] [HOTFIX] Update Cluster Autoscaler version
  cluster/manifests/kube-cluster-autoscaler/daemonset.yaml
Labels: bugfix

#9736 Revert "[STABLE] Revert "beta to stable""
  cluster/manifests/02-skipper-validation-webhook/deployment.yaml
  cluster/manifests/skipper/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
  test/e2e/go.mod
Labels: major
