Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-03, with the labels that each got.

#8985 pkg/converter: support zero ratelimit
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#9017 Kube proxy config cleanup
  cluster/manifests/kube-proxy/configmap.yaml
Labels: minor

#9012 Update to Karpenter v1.3.0
  cluster/cluster.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#9015 Shorten deployment-status-service url [1/3]
  cluster/manifests/deployment-service/status-service-ingress.yaml
Labels: minor

#8871 Handle secret read clusterroles
  cluster/manifests/02-admission-control/teapot.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/deployment-service/controller-rbac.yaml
  cluster/manifests/roles/cdp-deployer-binding.yaml
  cluster/manifests/roles/poweruser-role.yaml
Labels: bugfix

#9006 Slow down coredns shutdown
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#9008 Run e2e tests for both `zalando-aws` and `zalando-eks` providers.
  cluster/cluster.yaml
  delivery.yaml
  test/e2e/apply/config.yaml
  test/e2e/authorization.go
  test/e2e/run_e2e.sh
Labels: minor

#9025 Revert "Update to Karpenter v1.3.0"
  cluster/cluster.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: bugfix

#9020 Add option to bump wiz sensor daemonset priority class
  cluster/config-defaults.yaml
  cluster/manifests/wiz/sensor-daemonset.yaml
Labels: minor

#9030 Drop legacy skipper probe url
  cluster/manifests/skipper/routegroup-probe.yaml
Labels: minor

#9037 Update kube-node-decommissioner CronJob concurrencyPolicy to Replace
  cluster/manifests/kube-node-decommissioner/cronjob.yaml
Labels: bugfix

#8940 Allow access to secretsmanager:GetSecretValue for ZMON role
  cluster/cluster.yaml
Labels: minor

#9033 Avoid problem of anchor-merging lists by using multiple envFroms
  delivery.yaml
  test/e2e/apply/config.yaml
Labels: experiment, minor

#9016 Point to shorter deployment-status url [2/3]
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#9059 Allow collaborators write access in collaborator namespaces
  cluster/cluster.yaml
  cluster/manifests/02-admission-control/teapot.yaml
  test/e2e/authorization.go
Labels: bugfix

#9050 fabric-gateway: update CRD to support zero ratelimit for custom routes
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#9071 Disable resource protection via admission-controller in legacy clusters
  cluster/config-defaults.yaml
Labels: minor

#9076 Revert "Disable resource protection via admission-controller in legacy clusters"
  cluster/config-defaults.yaml
Labels: minor

#9090 eks: Enable control plane logging by default
  cluster/config-defaults.yaml
Labels: minor

#9094 eks: Make unbound work in ipv4 and ipv6 clusters
  cluster/manifests/01-coredns-local/configmap-local.yaml
  cluster/manifests/01-coredns-local/daemonset-coredns.yaml
Labels: bugfix

#9089 Toggle Emergency Access Service
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/emergency-access-service/01-rbac.yaml
  cluster/manifests/emergency-access-service/credentials.yaml
  cluster/manifests/emergency-access-service/deployment.yaml
  cluster/manifests/emergency-access-service/ingress.yaml
  cluster/manifests/emergency-access-service/service.yaml
Labels: minor

#9093 eks: Fix disabling control plane logging
  cluster/cluster.yaml
Labels: bugfix

#9101 Drop karpenter taint injection via admission-controller
  cluster/manifests/02-admission-control/config.yaml
  cluster/manifests/02-admission-control/deployment.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#9095 Switch to unbound_exporter for metrics
  cluster/config-defaults.yaml
  cluster/manifests/01-coredns-local/configmap-local.yaml
  cluster/manifests/01-coredns-local/daemonset-coredns.yaml
Labels: minor

#9092 eks: Break circular dependency on bootstrap
  cluster/manifests/02-admission-control/teapot.yaml
  cluster/manifests/02-skipper-validation-webhook/skipper-webhook.yaml
  cluster/manifests/external-dns/deployment.yaml
  cluster/manifests/ingress-controller/deployment.yaml
  cluster/manifests/zalando-iam-aws-proxy/deployment.yaml
Labels: major

#9106 Give api-monitoring-controller access to kube-system configmap
  cluster/manifests/02-admission-control/teapot.yaml
Labels: bugfix

#9107 [HOTFIX/alpha] Give api-monitoring-controller access to kube-system configmap
  cluster/manifests/02-admission-control/teapot.yaml
Labels: bugfix

#9108 [HOTFIX/beta] Give api-monitoring-controller access to kube-system configmap
  cluster/manifests/02-admission-control/teapot.yaml
Labels: bugfix

#8510 eks: Optional support for AWS VPC CNI Custom Networking
  cluster/config-defaults.yaml
  cluster/manifests/01-aws-node/daemonset.yaml
  cluster/manifests/01-aws-node/pod_subnets.yaml
  cluster/manifests/deletions.yaml
Labels: minor

#9085 Extend test case to ensure that node pools can scale-out after cluster update
  cluster/manifests/e2e-resources/pool-reserve.yaml
  test/e2e/infra.go
Labels: minor

#9103 skipper: update main fleet to version v0.22.1-1111
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9040 Update to Karpenter v1.3.2
  cluster/cluster.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#9118 Apply RouteGroup CRD after admission-control
  cluster/manifests/02-routegroup/routegroup-crd.yaml
Labels: bugfix

#9131 set karpenter_pools_enabled to true by default
  cluster/config-defaults.yaml
Labels: minor

#9137 Fix indentation to make template valid
  cluster/manifests/deployment-service/controller-rbac.yaml
Labels: bugfix

#9127 drop karpenter_pools_enabled config-item
  cluster/cluster.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/z-karpenter/01-serviceaccount.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/03-rolebinding.yaml
  cluster/manifests/z-karpenter/04-clusterrole.yaml
  cluster/manifests/z-karpenter/05-clusterrole-core.yaml
  cluster/manifests/z-karpenter/06-aggregate-clusterrole.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/manifests/z-karpenter/poddisruptionbudget.yaml
  cluster/manifests/z-karpenter/service.yaml
  cluster/manifests/z-karpenter/vpa.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  test/e2e/cluster_config.sh
Labels: minor

#9146 add nitro requirement for Karpenter pools
  cluster/config-defaults.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#9142 Reduce WIZ resources
  cluster/config-defaults.yaml
Labels: minor

#9150 admission-control: allow routesrv proxy
  cluster/manifests/02-admission-control/teapot.yaml
Labels: major

#9154 Fix typo in operator `in` => `In`
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix
