Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-02, with the labels that each got.

#8854 Give more time for the routing change
  test/e2e/aaas.go
  test/e2e/util.go
Labels: minor

#8857 Allow powerusers to use the subjectaccessreviews API
  cluster/manifests/roles/poweruser-role.yaml
Labels: minor

#8875 skipper-ingress: Use correct annotation for eks
  cluster/manifests/skipper/01-rbac.yaml
Labels: bugfix

#8881 efa-plugin: use label selector: vpc.amazonaws.com/efa: enabled
  cluster/manifests/aws-efa-device-plugin/daemonset.yaml
Labels: minor

#8879 feat: add new config item wiz_enable_runtime_connector_broker
  cluster/config-defaults.yaml
  cluster/manifests/wiz/connector-deployment.yaml
Labels: minor

#8861 feat: Update WIZ Job and WIZ DS
  cluster/manifests/wiz/005-connector-job.yaml
  cluster/manifests/wiz/sensor-daemonset.yaml
Labels: minor

#8890 feat: Update WIZ Broker and Connector Job resources
  cluster/manifests/wiz/002-connector-broker-serviceaccount.yaml
  cluster/manifests/wiz/003-connector-broker-clusterrole.yaml
  cluster/manifests/wiz/004-connector-broker-secrets.yaml
Labels: bugfix

#8891 Add kube-node-decommissioner CronJob
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/kube-node-decommissioner/01-rbac.yaml
  cluster/manifests/kube-node-decommissioner/cronjob.yaml
Labels: minor

#8880 Update to VPA 1.3.0
  cluster/manifests/01-vertical-pod-autoscaler/01-crd.yaml
  cluster/manifests/01-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/01-vertical-pod-autoscaler/updater-deployment.yaml
Labels: major

#8914 kube-node-decommissioner: fix image
  cluster/manifests/kube-node-decommissioner/cronjob.yaml
Labels: bugfix

#8929 Fix permissions for kube-node-decommissioner
  cluster/manifests/kube-node-decommissioner/01-rbac.yaml
Labels: bugfix

#8934 Enable postgresql owning-application annotation check in prod
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/manifests/01-admission-control/teapot.yaml
Labels: major

#8900 Update to Karpenter v1.0.5 [1/X]
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/01-admission-control/config.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/z-karpenter/01-serviceaccount.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/03-rolebinding.yaml
  cluster/manifests/z-karpenter/04-clusterrole.yaml
  cluster/manifests/z-karpenter/05-clusterrole-core.yaml
  cluster/manifests/z-karpenter/06-aggregate-clusterrole.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/manifests/z-karpenter/poddisruptionbudget.yaml
  cluster/manifests/z-karpenter/secret-webhook-cert.yaml
  cluster/manifests/z-karpenter/service.yaml
  cluster/manifests/z-karpenter/v1-migrator-cronjob.yaml
Labels: major

#8939 Increase resources for kube-node-decommissioner and make configurable
  cluster/config-defaults.yaml
  cluster/manifests/kube-node-decommissioner/cronjob.yaml
Labels: bugfix

#8943 Optional support for AWS Fault Injection Service with EKS
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deletions.yaml
  cluster/manifests/eks-fis/01-rbac.yaml
Labels: minor

#8883 fabric: update crd
  cluster/manifests/fabric-gateway/fabricgateway_crd.yaml
Labels: minor

#8901 Pre karpenter v1.1.1 changes [2/x]
  cluster/manifests/z-karpenter/v1-migrator-cronjob.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: major

#8954 Fix karpenter CRDs for v1.1.1 upgrade
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: bugfix

#8953 update to etcd v3.5.18
  cluster/config-defaults.yaml
Labels: minor

#8963 Halt terminating unbound
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#8969 Fix typo in lifecycle
  cluster/manifests/coredns-local/daemonset-coredns.yaml
Labels: bugfix

#8902 Update to Karpenter v1.1.1 [3/x]
  cluster/manifests/deletions.yaml
  cluster/manifests/z-karpenter/02-role.yaml
  cluster/manifests/z-karpenter/03-rolebinding.yaml
  cluster/manifests/z-karpenter/05-clusterrole-core.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
  cluster/manifests/z-karpenter/secret-webhook-cert.yaml
  cluster/manifests/z-karpenter/service.yaml
  cluster/manifests/z-karpenter/v1-migrator-cronjob.yaml
Labels: major

#8970 Update Karpenter for v1.1.1 on EKS
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
Labels: minor

#8981 use alias-independent variable for the hosted zone
  cluster/manifests/deployment-service/01-config.yaml
  cluster/manifests/skipper/routegroup-probe.yaml
Labels: minor

#8980 skipper: make hostname-credentials-controller resources configurable
  cluster/config-defaults.yaml
  cluster/manifests/skipper/hostname-credentials-controller.yaml
Labels: minor

#8984 dev to eks
  cluster/manifests/deletions.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#8530 Test eks ipv6 cluster
  test/e2e/external_dns.go
  test/e2e/run_e2e.sh
Labels: do-not-merge, minor
