Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-06, with the labels that each got.

#9493 Open up worker-to-worker communication
  cluster/cluster.yaml
Labels: minor

#9479 admission-control: enable ingress and routegroup admission
  cluster/config-defaults.yaml
  cluster/manifests/02-admission-control/teapot.yaml
Labels: major

#9508 Set increased WIZ Priority as default
  cluster/config-defaults.yaml
Labels: minor

#9494 Enable and allow to configure feature gate for image volumes
  cluster/config-defaults.yaml
  cluster/manifests/kube-proxy/configmap.yaml
  cluster/node-pools/master-default/userdata.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
Labels: minor

#9490 skipper-internal: Update main fleet to version v0.22.43-1150
  cluster/manifests/skipper/deployment.yaml
Labels: minor, dependencies

#9540 Update Karpenter to v1.5.0
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: minor

#9547 Make deployment-service's S3 bucket name configurable
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#9553 Make deployment-service's ML experimentation role name configurable
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#9573 increase subdomain_max_length for stups-test
  cluster/config-defaults.yaml
Labels: bugfix

#9580 Remove TopologyAwareHints Feature Flag
  cluster/config-defaults.yaml
  cluster/manifests/kube-proxy/configmap.yaml
  cluster/node-pools/master-default/userdata.yaml
Labels: minor

#9585 drop subdomain_max_length config for stups-test
  cluster/config-defaults.yaml
Labels: minor

#9597 skipper-internal: Update main to version v0.22.52-1159
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, minor, documentation, dependencies

#9582 expose-opa-ast-optimization-configuration-per-cluster
  cluster/config-defaults.yaml
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9619 Allow update of pods/ephemeralcontainers
  cluster/manifests/roles/poweruser-role.yaml
Labels: minor
