Repository zalando-incubator/kubernetes-on-aws, pull requests merged in 2025-05, with the labels that each got.

#9308 skipper: use internal CIDRs variable for healthcheck routes
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9345 skipper: update main to v0.22.21
  cluster/manifests/skipper/deployment.yaml
Labels: major, minor, dependencies

#9347 security: update Control Plane default ssl policy to `ELBSecurityPolicy-TLS13-1-2-2021-06`
  cluster/cluster.yaml
Labels: architectural, minor

#9344 Update VPA components to v1.3.1
  cluster/manifests/02-vertical-pod-autoscaler/admission-controller-deployment.yaml
  cluster/manifests/02-vertical-pod-autoscaler/recommender-deployment.yaml
  cluster/manifests/02-vertical-pod-autoscaler/updater-deployment.yaml
Labels: minor

#9314 security: update Ingress default ssl policy `ELBSecurityPolicy-TLS13-1-2-2021-06`
  cluster/config-defaults.yaml
Labels: minor

#9360 Update Karpenter to v1.4.0
  cluster/manifests/z-karpenter/01-serviceaccount.yaml
  cluster/manifests/z-karpenter/07-karpenter.k8s.aws_ec2nodeclasses.yaml
  cluster/manifests/z-karpenter/08-karpenter.sh_nodeclaims.yaml
  cluster/manifests/z-karpenter/09-karpenter.sh_nodepools.yaml
  cluster/manifests/z-karpenter/deployment.yaml
Labels: major

#9241 skipper-ingress: disable automated healthcheck routes
  cluster/manifests/skipper/deployment.yaml
Labels: do-not-merge, major

#8722 Update to Kubernetes v1.32
  cluster/cluster.yaml
  cluster/config-defaults.yaml
  cluster/manifests/aws-cloud-controller-manager/daemonset.yaml
  cluster/node-pools/master-default/stack.yaml
  cluster/node-pools/worker-combined/stack.yaml
  cluster/node-pools/worker-karpenter/provisioners.yaml
  cluster/node-pools/worker-splitaz/stack.yaml
  cluster/node-pools/worker-splitaz/userdata.yaml
  test/e2e/Dockerfile
  test/e2e/Makefile
  test/e2e/go.mod
  test/e2e/go.sum
Labels: major

#9387 skipper-internal: Update main to version v0.22.24-1131
  cluster/manifests/skipper/deployment.yaml
Labels: bugfix, major, minor, dependencies

#9351 Add e2e admission-controller role access tests
  cluster/cluster.yaml
  cluster/manifests/02-visibility/01-namespace.yaml
  test/e2e/authorization.go
Labels: minor

#9426 admission: use builtin preStop sleep
  cluster/manifests/02-admission-control/deployment.yaml
  cluster/manifests/02-skipper-validation-webhook/deployment.yaml
Labels: minor

#9424 feature: add OTel backend address in proxy span [1/2]
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9427 Provide default OIDC trust relationship template as a deployment variable
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#9456 Add the cluster's provider to deployment-config
  cluster/manifests/deployment-service/01-config.yaml
Labels: minor

#9475 feature: add OTel backend address in proxy span [2/2]
  cluster/manifests/skipper/deployment.yaml
Labels: minor

#9468 Include both authentication providers in trust relationship template variable
  cluster/config-defaults.yaml
  cluster/manifests/deployment-service/01-config.yaml
  test/e2e/cluster_config.sh
Labels: minor
